// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { MetaValue } from "./MetaValue";

/**
 * Error type for the parser
 */
export type ParserError =
    | { Unexpected: string }
    | "SyntaxUnexpected"
    | { SyntaxUnexpectedExpecting: string }
    | "SyntaxUnexpectedEof"
    | { InvalidItem: string }
    | "InvalidEmptyItem"
    | { IntFormat: string }
    | { FloatFormat: string }
    | { UnusedMetaKey: string }
    | { InvalidMetaValue: [string, MetaValue] }
    | { InvalidWeaponModifier: string }
    | { InvalidCookEffect: string }
    | "TooManyIngredients"
    | { InvalidArmorStarNum: number }
    | { InvalidSlotClause: number }
    | { InvalidTimesClause: number }
    | { InvalidTrial: string }
    | { InvalidCategory: Category }
    | { InvalidInventoryRow: number }
    | { InvalidInventoryCol: number };
