version: '3'

env:
  # can be overriden in .env
  DEBUG_ADDR: 192.168.0.161:5001
dotenv: [".env"]

tasks:
  live:
    desc: Connect to live trace
    cmds:
      - cargo run --release -- -c $DEBUG_ADDR {{.CLI_ARGS}}

  run:
    desc: Run trace viewer
    cmds:
      - cargo run --release -- {{.CLI_ARGS}}
