version: '3'

tasks:
  live:
    desc: Connect to live trace
    cmds:
      - cargo run --release -- -c $DEBUG_ADDR {{.CLI_ARGS}}

  run:
    desc: Run trace viewer
    cmds:
      - cargo run --release -- {{.CLI_ARGS}}
