[package]
name = "intwc-typescript-tokenizer"
description = "TypeScript tokenizer for intwc, powered by SWC"
version = "0.0.0"
edition = "2021"

[dependencies]
intwc-semantic-tokens = { path = "../semantic-tokens" }
js-sys = "0.3.76"
swc_common = "5.0.0"
swc_core = { version = "9.0.0", features = ["ecma_ast"] }
swc_ecma_parser = "6.0.0"
wasm-bindgen = "0.2.99"

[lib]
crate-type = ["cdylib", "rlib"]
