version: '3'

tasks:
  build:
    cmds:
      - bun scripts/build-themes.ts > src/theme/colors.ts

  patch-monaco-editor:
    cmds:
      - rm -rf monaco-editor-patch
      - pnpm install
      - pnpm patch monaco-editor@$(jq '.dependencies.["monaco-editor"]' package.json | tr -d '"') --edit-dir monaco-editor-patch > out
      - rm out
      - bun scripts/patch.ts
      - rm -r monaco-editor-patch/dev
      - rm -r monaco-editor-patch/min
      - rm -r monaco-editor-patch/min-maps
      - pnpm patch-commit monaco-editor-patch || true
      - rm -rf patches
      - mv ../../patches .
      - bun scripts/post-patch.ts
      - pnpm install
      - rm -rf monaco-editor-patch
