name: "Item Assets Cache Setup"
description: "Item Assets Cache Setup"

runs:
  using: composite
  steps:
    - uses: Pistonight/mono-dev/actions/permanent-cache@main
      with:
        path: packages/item-assets/public
        key: item-assets
      task: exec -- item-assets:pull-artifacts
      runner: blacksmith
