[package]
name = "skybook-runtime-tests"
version = "0.0.0"
edition = "2024"

[dependencies.blueflame]
path = "../blueflame"

[dependencies.skybook-runtime]
path = "../runtime"

[dependencies.skybook-parser]
path = "../parser"

[dependencies]
cu = { workspace = true, features = ["cli", "fs", "coroutine-heavy"] }
num_cpus = "1.17.0"
oneshot.workspace = true
sha2.workspace = true
threadpool = "1.8.1"

[features]
default = [
    "trace-memory",
    # "single-thread"
]
trace-memory = ["skybook-runtime/trace-memory"]
single-thread= []
