[package]
name = "skybook-runtime-tests"
version = "0.0.0"
edition = "2024"

[dependencies.blueflame]
path = "../blueflame"

[dependencies.skybook-runtime]
path = "../runtime"

[dependencies.skybook-parser]
path = "../parser"

[dependencies.cu]
version = "0.2.1" 
git = "https://github.com/Pistonight/cu"
# path = "../../../cu/packages/copper"
features = ["cli", "coroutine", "fs"]

[dependencies]
clap.workspace = true
num_cpus = "1.17.0"
oneshot = "0.1.11"
sha2.workspace = true
threadpool = "1.8.1"
tokio.workspace = true

[features]
default = [
    "trace-memory",
    # "blueflame/trace-call",
    "single-thread" # scheduling issue, way faster with just 1 thread
]
trace-memory = ["blueflame/trace-memory"]
single-thread= []
