[package]
name = "skybook-runtime-tests"
version = "0.0.0"
edition = "2024"

[dependencies.blueflame]
path = "../blueflame"

[dependencies.skybook-runtime]
path = "../runtime"

[dependencies.skybook-parser]
path = "../parser"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
num_cpus = "1.17.0"
oneshot = "0.1.11"
sha2.workspace = true
threadpool = "1.8.1"
tokio = { workspace = true, features = ["rt"] }

[features]
default = [
    "trace-memory",
    # "blueflame/trace-call",
    # "single-thread"
]
trace-memory = ["blueflame/trace-memory"]
single-thread= []
