import os
import yaml
SELF_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
RESEARCH_SCRIPTS_DIR = os.path.join(os.path.dirname(SELF_DIR), "research-scripts")
if not os.path.exists(RESEARCH_SCRIPTS_DIR):
    raise Exception(f"botw-research-scripts not found: {RESEARCH_SCRIPTS_DIR}")

HEADER = """// This file is auto-generated by scripts/build-armor-upgrade.py
// DO NOT EDIT MANUALLY
"""

OUTPUT_DIR = os.path.join(SELF_DIR, "src", "data")

def generate_armor_upgrade():
    armor_upgrade_path = os.path.join(RESEARCH_SCRIPTS_DIR, "output", "armor-upgrades.yaml")
    with open(armor_upgrade_path, "r", encoding="utf-8") as f:
        armor_upgrade = yaml.safe_load(f)

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
    
    output_path = os.path.join(OUTPUT_DIR, "armor_upgrade.gen.rs")

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        f.write("""
/// Armor upgrade data, each slice is from 0 star to 4 star
#[rustfmt::skip]
pub static ARMOR_UPGRADE: &[[&str; 5]] = &[
""")
        for group in armor_upgrade:
            f.write("    [")
            f.write(", ".join([f'{f'"{x}"':11}' for x in group]))
            f.write("],\n")
        f.write("];\n")

if __name__ == "__main__":
    generate_armor_upgrade()
