version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true
  cargo:
    taskfile: ./node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true
  git:
    taskfile: ./node_modules/mono-dev/task/git.yaml
    internal: true
    optional: true
    

tasks:
  check:
    desc: Run linters to check the code
    cmds:
      # bindings are needed to generate the files to check
      - task: build-ts-binding
      - task: build-workex-binding
      - task: ecma:check
      - task: cargo:clippy-all
      - task: cargo:fmt-check
  build:
    desc: Build the project
    cmds:
      - task: build-ts-binding
      - task: build-workex-binding
      - task: ecma:lib-build

  build-ts-binding:
    internal: true
    env:
      LC_ALL: C # consistent sort order
    cmds:
      - rm -f bindings/* src/native/*.ts
      - cargo test --lib --features __ts-binding
      - find bindings -type f | sort | sed 's/^bindings/export * from "./' | sed 's/$/";/' > src/native/index.ts
      - mv bindings/*.ts src/native

  build-workex-binding:
    internal: true
    vars:
      VERSION:
        sh: jq '.version' package.json | tr -d '"'
    cmds:
      - > 
        workex -p skybapi-{{.VERSION}} --prefix skybook
        -l Extension,ExtensionApp
        -l Runtime,RuntimeApp
        src/protocol/extension_api.ts 
        src/protocol/extension_app.ts 
        src/protocol/runtime_api.ts
        src/protocol/runtime_app.ts

  fix:
    desc: Fix style issues
    cmds:
      - task: ecma:fix
      - task: cargo:fmt-fix

  test:
    desc: Run tests
    cmds:
      - task: ecma:test

  dev:
    desc: Start development server
    cmds:
      - task: ecma:test-dev

  publish:
    desc: Publish a release
    cmds:
      - pnpm publish --access public
