version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
  git:
    taskfile: ../mono-dev/task/git.yaml
    internal: true
    

tasks:
  build:
    vars:
      VERSION:
        sh: jq '.version' package.json | tr -d '"'
    cmds:
      - task: build-ts-binding
      - > 
          workex -p skyb-api-{{.VERSION}} --prefix skybook --no-gitignore
          -l Extension,ExtensionApp -l Runtime,RuntimeApp
          src/extension_api.ts 
          src/extension_app.ts 
          src/runtime_api.ts
          src/runtime_app.ts
      - task: fix

  build-ts-binding:
    env:
      LC_ALL: C # consistent sort order
    cmds:
      - rm -f bindings/* src/native/*
      - cargo test --lib --features __ts-binding
      - $(which mkdir) -p src/native
      - find bindings -type f | sort | sed 's/^bindings/export * from "./' | sed 's/$/";/' > src/native/index.ts
      - mv bindings/*.ts src/native

  check:
    cmds:
      - task: build
      - task: git:check-modification
        vars:
          CHECK_PATH: packages/skybook-api/src
          CHECK_MESSAGE: Please regenerate and commit skybook-api bindings
      - task: ecma:mono-check
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: ecma:mono-fix
      - task: cargo:fmt-fix

  test:
    cmds:
      - task: ecma:vitest

  dev:
    cmds:
      - task: ecma:vitest-watch
