/**
 * This file is generated by workex
 */
import { type WorkexBindOptions, bindHost } from "@pistonite/workex";
import type { RuntimeAppHost } from "../RuntimeAppHost.ts";

export function bindRuntimeAppHostHost(delegate: RuntimeAppHost, options: WorkexBindOptions) {
    return bindHost("runtime", options, (fId: number, _payload: any[]) => {
        switch (fId) {
            case 23 /* RuntimeAppHost.resolveQuotedItem */: {
                const [ a0 ] = _payload;
                return delegate.resolveQuotedItem( a0 );
            }
        }
        return undefined;
    });
}