[workspace]
resolver = "2"
members = [
    # "packages/blueflame", 
    "packages/blueflame-deps", 
    "packages/blueflame-proc-macros", 
    # "packages/manual",
    "packages/parser", 
    # "packages/runtime",
    # "packages/runtime-tests",
    # "packages/runtime-wasm",
    "packages/skybook-api",
]

[workspace.dependencies]
cached = "0.59.0"
enumset = "1.1.8"
indoc = "2.0.7"
log = "0.4.27"
oneshot = "0.1.11"
phf = "0.13.1"
serde = "1"
sha2 = "0.10.9"
static_assertions = "1.1.0"
teleparse = "0.1.2"
textdistance = "1.1.1"
thiserror = "2.0.18"
tokio = "1"

# Rust-Web ecosystem
js-sys = "0.3.95"
ts-rs = "11.1.0"
tsify = { version = "0.5.6", features = ["js"], default-features = false }
wasm-bindgen = { version = "0.2.118", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.68"

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.8.2"

[workspace.dependencies.pm]
package = "pistonite-pm"
version = "0.2.6"
