packages:
  - packages/app
  - packages/intwc
  - packages/intwc/vite-plugin
  - packages/itemsys
  - packages/itemsys-build
  - packages/localization
  - packages/mono-dev
  - packages/parser-legacy
  - packages/runtime-wasm
  - packages/runtime-worker
  - packages/server
  - packages/shared-controls
  - packages/skybook-api

catalog:
  '@fluentui/react-components': ^9.70.0
  '@fluentui/react-icons': ^2.0.311
  '@griffel/react': ^1.5.30
  '@modyfi/vite-plugin-yaml': ^1.1.1
  '@pistonite/pure': ^0.28.0
  '@pistonite/pure-i18next': ^0.5.0
  '@pistonite/pure-react': ^0.8.0
  '@pistonite/workex': ^0.1.5
  '@types/bun': ^1.2.23
  '@types/react': ^18.3.17
  '@types/react-dom': ^18.3.5
  '@vitejs/plugin-react': ^4.7.0
  i18next: ^25.5.2
  lru-cache: ^11.2.2
  react: ^18.3.1
  react-dom: ^18.3.1
  react-i18next: ^16.0.0
  typescript: ^5.9.2
  uuid: ^13.0.0
  vite: ^6.3.6
  vitest: ^3.2.4
