packages:
  - packages/app
  - packages/extension-api
  - packages/intwc
  - packages/item-assets
  - packages/item-system
  - packages/localization
  - packages/mono-dev
  - packages/parser
  - packages/runtime-api
  - packages/runtime-wasm
  - packages/shared-controls

catalog:
  "@griffel/react": ^1.5.29
  "@fluentui/react-components": ^9.58.2
  "@fluentui/react-icons": ^2.0.271
  "@modyfi/vite-plugin-yaml": ^1.1.0
  "@pistonite/pure": ^0.22.1
  "@pistonite/pure-react": ^0.7.0
  "@pistonite/pure-i18next": ^0.3.0
  "@pistonite/workex": ^0.0.5
  "@types/react": ^18.3.17
  "@types/react-dom": ^18.3.5
  "@vitejs/plugin-react": ^4.3.4
  eslint: ^9
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ^5.7.2
  vite: ^5.4.14

