packages:
  # - packages/app
  # - packages/intwc
  # - packages/intwc/vite-plugin
  - packages/itemsys
  # - packages/localization
  # - packages/parser-legacy
  # - packages/runtime-wasm
  # - packages/runtime-worker
  # - packages/server
  - packages/skybook-api

catalog:
  mono-dev: github:pistonight/mono-dev#dist
  '@pistonite/pure': ^0.29.5
  '@pistonite/celera': ^0.1.3
  '@pistonite/workex': ^0.2.1
  lru-cache: ^11.3.5
  react: ^19.2.5
  react-dom: ^19.2.5
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@fluentui/react-components': ^9.73.8
  '@fluentui/react-icons': ^2.0.324

  '@griffel/react': ^1.5.30
  '@types/bun': ^1.2.23
  '@vitejs/plugin-react': ^4.7.0
  i18next: ^25.5.2
  react-i18next: ^16.0.0
  typescript: ^5.9.2
  uuid: ^13.0.0
  vite: ^6.3.6
  vitest: ^3.2.4
