packages:
  - packages/app
  - packages/intwc
  - packages/intwc/vite-plugin
  - packages/item-assets
  - packages/item-system
  - packages/localization
  - packages/mono-dev
  - packages/parser-legacy
  - packages/runtime-wasm
  - packages/runtime-worker
  - packages/server
  - packages/shared-controls
  - packages/skybook-api

catalog:
  "@griffel/react": ^1.5.30
  "@fluentui/react-components": ^9.64.0
  "@fluentui/react-icons": ^2.0.300
  "@modyfi/vite-plugin-yaml": ^1.1.1
  "@pistonite/pure": ^0.26.3
  "@pistonite/pure-react": ^0.7.9
  "@pistonite/pure-i18next": ^0.4.4
  "@types/bun": ^1.2.13
  "@pistonite/workex": ^0.1.0
  "@types/react": ^18.3.17
  "@types/react-dom": ^18.3.5
  "@vitejs/plugin-react": ^4.4.0
  i18next: ^25.1.3
  react-i18next: ^15.5.1
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.1.3

