packages:
  - packages/app
  - packages/intwc
  - packages/intwc/vite-plugin
  - packages/itemsys
  - packages/itemsys-build
  - packages/localization
  - packages/mono-dev
  - packages/parser-legacy
  - packages/runtime-wasm
  - packages/runtime-worker
  - packages/server
  - packages/shared-controls
  - packages/skybook-api

catalog:
  '@fluentui/react-components': ^9.68.2
  '@fluentui/react-icons': ^2.0.307
  '@griffel/react': ^1.5.30
  '@modyfi/vite-plugin-yaml': ^1.1.1
  '@pistonite/pure': ^0.27.1
  '@pistonite/pure-i18next': ^0.4.9
  '@pistonite/pure-react': ^0.7.13
  '@pistonite/workex': ^0.1.4
  '@types/bun': ^1.2.19
  '@types/react': ^18.3.17
  '@types/react-dom': ^18.3.5
  '@vitejs/plugin-react': ^4.4.0
  i18next: ^25.3.2
  lru-cache: ^11.1.0
  react: ^18.3.1
  react-dom: ^18.3.1
  react-i18next: ^15.6.1
  typescript: =5.8.3
  uuid: ^11.1.0
  vite: ^6.3.6
  vitest: ^3.2.4
