packages:
  - packages/intwc
  - packages/localization
  - packages/mono-dev
  - packages/workex

catalog:
  "@modyfi/vite-plugin-yaml": ^1.1.0
  "@pistonite/pure": ^0.0.18
  "@types/react": ^18.3.17
  eslint: ^9
  react: ^18.3.1
  typescript: ^5.7.2
  vite: ^5.4.14

