version: '3'

includes:
  app:
    taskfile: ./app
    dir: ./app

  manual:
    aliases: [man]
    taskfile: ./manual
    dir: ./manual

  legacy:
    aliases: [leg]
    taskfile: ./legacy
    dir: ./legacy

  server:
    taskfile: ./server
    dir: ./server

  trace:
    taskfile: ./research/trace
    aliases: [tr]
    dir: ./research/trace

  trace-view:
    taskfile: ./research/trace-view
    aliases: [trv]
    dir: ./research/trace-view

tasks:
  install:
    desc: Install tools
    cmds:
      - cargo install mdbook live-server cargo-watch wasm-pack

