version: '3'

includes:
  common: 
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true
    optional: true

  server:         {taskfile: ./packages/server,           dir: ./packages/server,           internal: true}
  app:            {taskfile: ./packages/app,              dir: ./packages/app,              internal: true}
  blueflame:      {taskfile: ./packages/blueflame,        dir: ./packages/blueflame,        internal: true}
  blueflame-deps: {taskfile: ./packages/blueflame-deps,   dir: ./packages/blueflame-deps,   internal: true}
  blueflame-proc-macros: {taskfile: ./packages/blueflame-proc-macros, dir: ./packages/blueflame-proc-macros, internal: true}
  runtime:        {taskfile: ./packages/runtime,          dir: ./packages/runtime,          internal: true}
  runtime-tests:  {taskfile: ./packages/runtime-tests,    dir: ./packages/runtime-tests,    internal: true}
  runtime-wasm:   {taskfile: ./packages/runtime-wasm,     dir: ./packages/runtime-wasm,     internal: true}
  runtime-worker: {taskfile: ./packages/runtime-worker,   dir: ./packages/runtime-worker,   internal: true}
  parser:         {taskfile: ./packages/parser,           dir: ./packages/parser,           internal: true}
  parser-legacy:  {taskfile: ./packages/parser-legacy,    dir: ./packages/parser-legacy,    internal: true}
  itemsys:        {taskfile: ./packages/itemsys,          dir: ./packages/itemsys,          internal: true}
  itemsys-build:  {taskfile: ./packages/itemsys-build,    dir: ./packages/itemsys-build,    internal: true}
  skybook-api:    {taskfile: ./packages/skybook-api,      dir: ./packages/skybook-api,      internal: true}
  research:       {taskfile: ./packages/research-scripts, dir: ./packages/research-scripts, internal: true}
  localization:   {taskfile: ./packages/localization,     dir: ./packages/localization,     internal: true}
  manual:         {taskfile: ./packages/manual,           dir: ./packages/manual,           internal: true}
  intwc:          {taskfile: ./packages/intwc,            dir: ./packages/intwc,            internal: true}
  shared-controls: {taskfile: ./packages/shared-controls, dir: ./packages/shared-controls,  internal: true}

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: mdbook mdbook-admonish live-server cargo-watch wasm-pack ripgrep layered-crate git-delta
      - task: cargo-binstall
        vars:
          PACKAGES: workex --git https://github.com/Pistonite/workex
      # only needed for regenerating app icons
      # - cargo install --git https://github.com/Pistonite/prism

  install:
    desc: Install packages for local development
    aliases: [i]
    cmds:
      - echo "nightly" > packages/runtime-wasm/rust-toolchain
      - magoo install
      - pnpm install
      - task: post-install

  post-install:
    cmds:
      - task: app:install
      - task: manual:install
      - task: intwc:install
      - task: shared-controls:install
      - task: server:install

  build-artifacts:
    desc: Generate artifacts for development locally
    cmds:
      - task: research:build
      - task: parser:bsource
      - task: itemsys:bsource
      - task: localization:build
      - task: runtime-wasm:pull-dist
      - task: blueflame-deps:build

  pull-artifacts:
    desc: Pull artifacts from storage (requires gcloud access)
    deps:
      - cache-ci-app-assets-pull-artifacts
      - cache-ci-runtime-pull-artifacts

  cache-ci-app-assets-pull-artifacts:
    deps:
      - localization:pull-artifacts
      - itemsys-build:pull-artifacts

  cache-ci-runtime-pull-artifacts:
    deps:
      - blueflame-deps:pull-artifacts
      - runtime-tests:pull-artifacts

  check-ci-layer-1-2:
    cmds:
      - pnpm install --frozen-lockfile
      - task: post-install
      - task: check-layer-1
      - task: check-layer-2

  check-ci-layer-3:
    cmds:
      - pnpm install --frozen-lockfile
      - task: post-install
      - task: check-layer-3

  check-ci-layer-4:
    cmds:
      - pnpm install --frozen-lockfile
      - task: post-install
      - task: check-layer-4

  check:
    desc: Run ALL of the checks
    cmds:
      - task: check-layer-1
      - task: check-layer-2
      - task: check-layer-3
      - task: check-layer-4
      - cmd: echo 'All checks passed!'
        silent: true

  check-layer-1:
    deps:
      - skybook-api:check

  check-layer-2:
    deps:
      - manual:check
      - localization:check
      - itemsys:check
      - app:check
      - server:check
      - runtime-worker:check

  check-layer-3:
    cmds:
      - task: parser:check
      - task: blueflame-proc-macros:check
      - task: blueflame-deps:check
      - task: blueflame:check
      - task: runtime:check
      - task: runtime-tests:check

  check-layer-4:
    cmds:
      - cmd: >
          if stat packages/runtime-tests/data/program-mini.bfi;
          then
            {{.TASK_EXE}} exec -- runtime-wasm:check;
          else
            echo "skipping checking runtime-wasm since no local image is found.";
          fi
        silent: true

  test-ci:
    cmds:
      - pnpm install --frozen-lockfile
      - task: post-install
      - task: test
      

  test:
    desc: Run ALL of the tests
    cmds:
      - task: test-layer-1
      - task: test-layer-2
      - cmd: echo 'All tests passed!'
        silent: true

  test-layer-2:
    cmds:
      - task: parser:test
      - task: blueflame-deps:test
      - task: blueflame:test
      - task: runtime-tests:run-mini

  test-layer-1:
    deps:
      - skybook-api:test
      - app:test

  build:
    desc: Check that components can build without failure
    deps:
      - app:build
      - server:build
    cmds:
      - task: manual:build
      - task: runtime-wasm:build

  build-manual-ci:
    cmds:
        # this technically isn't needed, but not installing pnpm
        # causes CI to be unreliable due to cache issues
        # (and I couldn't figure out how to optinally enable the setup)
      - pnpm install --frozen-lockfile 
      - task: manual:install
      - task: manual:build

  build-app-ci:
    cmds:
      - pnpm install --frozen-lockfile
      - task: intwc:install
      - task: app:install
      - task: app:build

  build-runtime-ci-pr:
    cmds:
      - pnpm install --frozen-lockfile
      - task: runtime-wasm:build
      - task: runtime-wasm:clean-dist # so we don't upload non-min bundles
      - task: runtime-wasm:build-dist-min

  build-runtime-ci:
    cmds:
      - pnpm install --frozen-lockfile
      - task: runtime-wasm:build-wasm
      - task: runtime-wasm:build-dist-min

  build-server-ci:
    cmds:
      - pnpm install --frozen-lockfile
      - task: server:install
      - task: server:build

  clean:
    desc: Clean the whole repo for temporaries that might help resolve build issues
    cmds:
      - rm -f rustc-ice-*
      - cargo clean
      - rustup update
      - task: runtime-wasm:clean
      - task: itemsys-build:clean

  publish:
    desc: Publish artifacts
    vars:
      SKYBOOK_VERSION_TAG:
        sh: echo "v"$(jq '.version' package.json | tr -d '"')
    cmds:
      - git tag {{.SKYBOOK_VERSION_TAG}}
      - git push origin {{.SKYBOOK_VERSION_TAG}}
      - task: skybook-api:publish
        ignore_error: true
