version: '3'

env:
  # can be overriden in .env
  DEBUG_ADDR: 192.168.0.161:5001
  CONSOLE_ADDR: 192.168.0.161:5000
dotenv: [".env"]

includes:
  app:
    taskfile: ./packages/app
    dir: ./packages/app

  monaco-editor:
    taskfile: ./packages/monaco-editor-contrib
    dir: ./packages/monaco-editor-contrib

  manual:
    aliases: [man]
    taskfile: ./manual
    dir: ./manual

  legacy:
    aliases: [leg]
    taskfile: ./legacy
    dir: ./legacy

  server:
    taskfile: ./server
    dir: ./server

  trace:
    taskfile: ./research/trace
    aliases: [tr]
    dir: ./research/trace

  trace-view:
    taskfile: ./research/trace-view
    aliases: [trv]
    dir: ./research/trace-view

tasks:
  npm-install:
    aliases: [npmi]
    desc: Wrapper for npm install to put everything in the right place
    cmds:
      - task: monaco-editor:clean
      - npm install
      - task: fix-npm-installs

  fix-npm-installs:
    cmds:
      - mv node_modules/monaco-editor packages/monaco-editor-contrib/lib
      - task: monaco-editor:patch



  install-tools:
    desc: Install tools
    cmds:
      - cargo install mdbook live-server cargo-watch wasm-pack

