version: '3'

env:
  # can be overriden in .env
  DEBUG_ADDR: 192.168.0.161:5001
  CONSOLE_ADDR: 192.168.0.161:5000
dotenv: [".env"]

includes:


  legacy:
    aliases: [leg]
    taskfile: ./legacy
    dir: ./legacy

  server:
    taskfile: ./server
    dir: ./server

  trace:
    taskfile: ./research/trace
    aliases: [tr]
    dir: ./research/trace

  trace-view:
    taskfile: ./research/trace-view
    aliases: [trv]
    dir: ./research/trace-view

  # new ones below

  app:
    taskfile: ./packages/app
    dir: ./packages/app
    internal: true

  runtime-wasm:
    taskfile: ./packages/runtime-wasm
    dir: ./packages/runtime-wasm
    internal: true

  parser:
    taskfile: ./packages/parser
    dir: ./packages/parser
    internal: true

  item-system:
    taskfile: ./packages/item-system
    dir: ./packages/item-system
    internal: true

  research:
    taskfile: ./packages/research-scripts
    dir: ./packages/research-scripts

  localization:
    taskfile: ./packages/localization
    dir: ./packages/localization
    internal: true

  item-assets:
    taskfile: ./packages/item-assets
    dir: ./packages/item-assets
    internal: true

  manual:
    taskfile: ./packages/manual
    dir: ./packages/manual
    internal: true





tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install magoo mdbook mdbook-admonish live-server cargo-watch wasm-pack
      - cargo install --git https://github.com/Pistonite/workex

  install:
    desc: Install packages for local development
    aliases: [i]
    cmds:
      - magoo install
      - task: install-deps
      - pnpm install
      - task: manual:install

  install-ci:
    cmds:
      - task: install-deps
      - pnpm install --frozen-lockfile
      - task: manual:install

  install-deps:
    deps:
      - localization:pull-artifacts
      - item-assets:pull-artifacts
      - item-system:pull-artifacts
      - parser:pull-artifacts

  check:
    deps:
      - localization:check
      - item-assets:check
      - item-system:check
      - parser:check
      - app:check
      

  test:
    cmds:
      - task: parser:test

