version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
    - npm i

  ast:
    desc: Generate AST parser (needs `python3`)
    cmds:
    - python3 generate_parser.py src/core/command/ast/grammar.txt src/core/command/ast/ast.generated.ts
    sources:
    - generate_parser.py
    - src/core/command/ast/grammar.txt
    generates:
    - src/core/command/ast/ast.generated.ts

  dev:
    desc: Run dev server
    deps: [ast]
    cmds:
    - npx vite --host

  check:
    desc: Check for errors
    cmds:
    - task: eslint
      vars:
        ESLINT_ARGS: ""
    - task: prettier
      vars:
        PRETTIER_ARGS: --check

  fix:
    desc: Fix errors
    cmds:
    - task: prettier
      vars:
        PRETTIER_ARGS: --write
    - task: eslint
      vars: 
        ESLINT_ARGS: --fix

  test:
    desc: Run tests (Jest arguments apply)
    cmds:
    - npx jest --config tools/test/jest.config.cjs {{.ARGS}}

  build:
    desc: Build production bundle
    deps: [ast]
    cmds:
    - npx tsc
    - npx vite build

  eslint:
    cmds:
    - npx eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0 --cache {{.ESLINT_ARGS}}

  prettier:
    cmds:
    - npx prettier "./**/*.{ts,tsx,json,js,jsx,cjs,css}" {{.PRETTIER_ARGS}}

