version: '3'

env:
  # can be overriden in .env
  DEBUG_ADDR: 192.168.0.161:5001
  CONSOLE_ADDR: 192.168.0.161:5000
dotenv: [".env"]

includes:
  app:
    taskfile: ./packages/app
    dir: ./packages/app

  monaco-editor:
    taskfile: ./packages/monaco-editor-contrib
    dir: ./packages/monaco-editor-contrib

  manual:
    aliases: [man]
    taskfile: ./manual
    dir: ./manual

  legacy:
    aliases: [leg]
    taskfile: ./legacy
    dir: ./legacy

  server:
    taskfile: ./server
    dir: ./server

  trace:
    taskfile: ./research/trace
    aliases: [tr]
    dir: ./research/trace

  trace-view:
    taskfile: ./research/trace-view
    aliases: [trv]
    dir: ./research/trace-view

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install mdbook live-server cargo-watch wasm-pack
      - cargo install --git https://github.com/Pistonite/workex

  install:
    desc: Install packages
    aliases: [i]
    cmds:
      - task: install-workex
      - pnpm i

  install-workex:
    cmds:
      - rm -rf packages/workex
      - workex --lib-out-path packages/workex --lib-package --lib-only

