version: '3'

env:
  # can be overriden in .env
  DEBUG_ADDR: 192.168.0.161:5001
  CONSOLE_ADDR: 192.168.0.161:5000
dotenv: [".env"]

includes:
  app:
    taskfile: ./packages/app
    dir: ./packages/app

  monaco-editor:
    taskfile: ./packages/monaco-editor-contrib
    dir: ./packages/monaco-editor-contrib

  manual:
    aliases: [man]
    taskfile: ./manual
    dir: ./manual

  legacy:
    aliases: [leg]
    taskfile: ./legacy
    dir: ./legacy

  server:
    taskfile: ./server
    dir: ./server

  trace:
    taskfile: ./research/trace
    aliases: [tr]
    dir: ./research/trace

  trace-view:
    taskfile: ./research/trace-view
    aliases: [trv]
    dir: ./research/trace-view

  research:
    taskfile: ./packages/research-scripts
    dir: ./packages/research-scripts
    optional: true

  localization:
    taskfile: ./packages/localization
    dir: ./packages/localization

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install magoo mdbook mdbook-admonish live-server cargo-watch wasm-pack
      - cargo install --git https://github.com/Pistonite/workex

  install:
    desc: Install packages for local development
    aliases: [i]
    cmds:
      - magoo install
      - task: install-workex
      - task: research:build
      - pnpm i
      - task: localization:build

  install-workex:
    cmds:
      - rm -rf packages/workex
      - workex --lib-out-path packages/workex --lib-package --lib-only

