version: '3'

includes:
  common: 
    taskfile: ./node_modules/mono-dev/task/common.yaml
    flatten: true
    optional: true

  server:         {taskfile: ./packages/server,           dir: ./packages/server,           internal: true}
  app:            {taskfile: ./packages/app,              dir: ./packages/app,              internal: true}
  blueflame:      {taskfile: ./packages/blueflame,        dir: ./packages/blueflame,        internal: true}
  blueflame-deps: {taskfile: ./packages/blueflame-deps,   dir: ./packages/blueflame-deps,   internal: true}
  blueflame-proc-macros: {taskfile: ./packages/blueflame-proc-macros, dir: ./packages/blueflame-proc-macros, internal: true}
  runtime:        {taskfile: ./packages/runtime,          dir: ./packages/runtime,          internal: true}
  runtime-tests:  {taskfile: ./packages/runtime-tests,    dir: ./packages/runtime-tests,    internal: true}
  runtime-wasm:   {taskfile: ./packages/runtime-wasm,     dir: ./packages/runtime-wasm,     internal: true, alias: "wasm"}
  runtime-worker: {taskfile: ./packages/runtime-worker,   dir: ./packages/runtime-worker,   internal: true}
  parser:         {taskfile: ./packages/parser,           dir: ./packages/parser,           internal: true}
  parser-legacy:  {taskfile: ./packages/parser-legacy,    dir: ./packages/parser-legacy,    internal: true}
  itemsys:        {taskfile: ./packages/itemsys,          dir: ./packages/itemsys,          internal: true}
  itemsys-build:  {taskfile: ./packages/itemsys-build,    dir: ./packages/itemsys-build,    internal: true}
  skybook-api:    {taskfile: ./packages/skybook-api,      dir: ./packages/skybook-api,      internal: true}
  localization:   {taskfile: ./packages/localization,     dir: ./packages/localization,     internal: true}
  manual:         {taskfile: ./packages/manual,           dir: ./packages/manual,           internal: true}

  # submodules
  data:  { taskfile: ./packages/botw-data, dir: ./packages/botw-data, internal: true, optional: true }

tasks:

  # -- setup tasks --
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: mdbook shwoop wasm-pack layered-crate
      - task: cargo-binstall
        vars:
          PACKAGES: workex --git https://github.com/Pistonite/workex
      # only needed for regenerating app icons
      # - cargo install --git https://github.com/Pistonite/prism

  install:
    desc: Install packages for local development
    aliases: [i]
    cmds:
      - magoo install
      - pnpm install
      - task: post-install
      - task: runtime-wasm:install

  post-install:
    cmds:
      - task: app:install
      - task: manual:install
      - task: server:install

  # -- artifacts tasks --
  build-artifacts:
    desc: Generate artifacts for development locally
    cmds:
      - task: data:build
      - task: parser:build-src
      - task: itemsys-build:pull-dist
      - task: runtime-wasm:pull-dist
      - task: blueflame-deps:build-src

  cache-ci-itemsys-pull-artifacts:
    deps:
      - itemsys-build:pull-artifacts

  cache-ci-runtime-pull-artifacts:
    deps:
      - blueflame-deps:pull-artifacts
      - runtime-tests:pull-artifacts

  # -- check tasks --
  check-ci-layer-1-2:
    cmds:
      - task: post-install
      - task: check-layer-1
      - task: check-layer-2

  check-ci-layer-3:
    cmds:
      - task: post-install
      - task: check-layer-3

  check-ci-layer-4:
    cmds:
      - task: post-install
      - task: check-layer-4

  check:
    desc: Run ALL of the checks
    cmds:
      - task: check-layer-1
      - task: check-layer-2
      - task: check-layer-3
      - task: check-layer-4
      - cmd: echo 'All checks passed!'
        silent: true

  check-layer-1:
    deps:
      - skybook-api:check

  check-layer-2:
    deps:
      - manual:check
      - localization:check
      - itemsys:check
      - app:check
      - server:check
      - runtime-worker:check

  check-layer-3:
    cmds:
      - task: parser:check
      - task: blueflame-proc-macros:check
      - task: blueflame-deps:check
      - task: blueflame:check
      - task: runtime:check
      - task: runtime-tests:check

  check-layer-4:
    cmds:
      - task: skybook-api:build-dep
      - cmd: >
          if stat packages/runtime-tests/data/program-mini.bfi;
          then
            {{.TASK_EXE}} exec -- runtime-wasm:check;
          else
            echo "skipping checking runtime-wasm since no local image is found.";
          fi
        silent: true

  test-ci:
    cmds:
      - task: post-install
      - task: test
      - task: skybook-api:test
      

  test:
    desc: Run ALL of the tests
    cmds:
      - task: skybook-api:test
      - task: app:test
      - task: itemsys:test
      - task: parser:test
      - task: blueflame-deps:test
      - task: blueflame:test
      - task: runtime-tests:run-mini
      - cmd: echo 'All tests passed!'
        silent: true

  build:
    desc: Check that components can build without failure
    cmds:
      - task: app:build
      - task: server:build
      - task: manual:build
      - task: runtime-wasm:build

  build-app-manual-server-ci:
    cmds:
      - task: app:install
      - task: manual:install
      - task: server:install
      - task: skybook-api:build-dep
      - task: app:build
      - task: manual:build
      - task: server:build

  build-app-server-ci:
    cmds:
      - task: app:install
      - task: server:install
      - task: skybook-api:build-dep
      - task: app:build
      - task: server:build

  build-manual-ci:
    cmds:
      - task: manual:install
      - task: manual:build

  build-runtime-ci-pr:
    cmds:
      - task: skybook-api:build-dep
      - task: runtime-wasm:build
      - task: runtime-wasm:clean-dist # so we don't upload non-min bundles
      - task: runtime-wasm:build-dist-min

  build-runtime-ci:
    cmds:
      - task: skybook-api:build-dep
      - task: runtime-wasm:build-wasm
      - task: runtime-wasm:build-dist-min

  clean:
    desc: Clean the whole repo for temporaries that might help resolve build issues
    cmds:
      - rm -f rustc-ice-*
      - cargo clean
      - rustup update
      - task: runtime-wasm:clean
      - task: itemsys-build:clean

  publish-app:
    desc: Publish artifacts
    vars:
      SKYBOOK_VERSION_TAG:
        sh: echo "v"$(jq '.version' package.json | tr -d '"')
    cmds:
      - git tag {{.SKYBOOK_VERSION_TAG}}
      - git push origin {{.SKYBOOK_VERSION_TAG}}

  publish-api:
    - task: skybook-api:publish
  publish-itemsys:
    - task: itemsys:publish

  pnpm-dev-link:
    cmds:
      - |
        for f in packages/*/package.json; do
          sed -i 's|"@pistonite/{{.CLI_ARGS}}": "catalog:"|"@pistonite/{{.CLI_ARGS}}": "link:../../../{{.CLI_ARGS}}"|g' "$f"
        done
      - pnpm i

  pnpm-dev-unlink:
    cmds:
      - |
        for f in packages/*/package.json; do
          sed -i 's|"@pistonite/{{.CLI_ARGS}}": "link:../../../{{.CLI_ARGS}}"|"@pistonite/{{.CLI_ARGS}}": "catalog:"|g' "$f"
        done
      - pnpm i

  upgrade:
    desc: Upgrade dependencies
    cmds:
      - >
        pnpm up -r mono-dev @pistonite/pure @pistonite/workex @pistonite/celera
        lru-cache
        react react-dom @types/react @types/react-dom
        @fluentui/react-components @fluentui/react-icons
        fuse.js js-yaml @types/js-yaml @types/node
        @types/bun zustand uuid reselect
        @uidotdev/usehooks @tanstack/react-query
      - pnpm dedupe
      - pnpm dedupe --check
      - cargo upgrade
