version: '3'

env:
  # can be overriden in .env
  DEBUG_ADDR: 192.168.0.161:5001
  CONSOLE_ADDR: 192.168.0.161:5000
dotenv: [".env"]

includes:

  server:
    taskfile: ./server
    dir: ./server

  trace:
    taskfile: ./research/trace
    aliases: [tr]
    dir: ./research/trace

  trace-view:
    taskfile: ./research/trace-view
    aliases: [trv]
    dir: ./research/trace-view

  # new ones below

  app:
    taskfile: ./packages/app
    dir: ./packages/app
    internal: true

  runtime-wasm:
    taskfile: ./packages/runtime-wasm
    dir: ./packages/runtime-wasm
    internal: true

  parser:
    taskfile: ./packages/parser
    dir: ./packages/parser
    internal: true

  parser-legacy:
    taskfile: ./packages/parser-legacy
    dir: ./packages/parser-legacy
    internal: true

  item-system:
    taskfile: ./packages/item-system
    dir: ./packages/item-system
    internal: true

  skybook-api:
    taskfile: ./packages/skybook-api
    dir: ./packages/skybook-api
    internal: true

  research:
    taskfile: ./packages/research-scripts
    dir: ./packages/research-scripts
    internal: true

  localization:
    taskfile: ./packages/localization
    dir: ./packages/localization
    internal: true

  item-assets:
    taskfile: ./packages/item-assets
    dir: ./packages/item-assets
    internal: true

  manual:
    taskfile: ./packages/manual
    dir: ./packages/manual
    internal: true

  intwc:
    taskfile: ./packages/intwc
    dir: ./packages/intwc
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install magoo mdbook mdbook-admonish live-server cargo-watch wasm-pack ripgrep
      - cargo install --git https://github.com/Pistonite/workex

  install:
    desc: Install packages for local development
    aliases: [i]
    cmds:
      - magoo install
      - pnpm install
      - task: post-install

  install-ci:
    cmds:
      - task: pull-artifacts
      - pnpm install --frozen-lockfile
      - task: post-install

  post-install:
    cmds:
      - task: parser-legacy:install
      - task: manual:install
      - task: intwc:install

  exec:
    aliases: [x]
    desc: Execute a task in a package (exec -- PACKAGE:TASK)
    cmds:
      - task: "{{.CLI_ARGS}}"

  list:
    aliases: [ls]
    desc: List tasks in a package (list -- PACKAGE)
    dir: "packages/{{.CLI_ARGS}}"
    silent: true
    cmds:
      - cmd: "{{.TASK_EXE}} --list"

  build-artifacts:
    desc: Generate artifacts for development locally and from hosted app
    cmds:
      - task: parser:pull-deps-public
      - task: item-assets:pull-artifacts-public
      - task: research:build
      - task: localization:build
      - task: item-assets:build-src
      - task: item-system:build
      - task: parser:build
      - task: runtime-wasm:pull-dist

  pull-artifacts:
    desc: Pull artifacts from storage (requires gcloud access)
    deps:
      - localization:pull-artifacts
      - item-assets:pull-artifacts
      - item-system:pull-artifacts
      - parser:pull-artifacts

  check:
    desc: Run ALL of the checks
    cmds:
      - task: check-layer-1
      - task: check-layer-2
      - task: check-layer-3
      - cmd: echo 'All checks passed!'
        silent: true

  check-layer-1:
    deps:
      - skybook-api:check

  check-layer-2:
    deps:
      - manual:check
      - localization:check
      - item-system:check
      - app:check

  check-layer-3:
    deps:
      - parser:check
      # - task: runtime:check
      # - task: runtime-wasm:check
      

  test:
    desc: Run ALL of the tests
    deps:
      - item-system:test
    cmds:
      - task: parser:test

  build:
    desc: Check that components can build without failure
    deps: []
      # - app:build
    cmds:
      - task: manual:build
      - task: runtime-wasm:build

