version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
    - npm i

  ast:
    desc: Generate AST parser (needs `python3`)
    cmds:
    - python3 generate_parser.py src/core/command/ast/grammar.txt src/core/command/ast/ast.generated.ts
    sources:
    - generate_parser.py
    - src/core/command/ast/grammar.txt
    generates:
    - src/core/command/ast/ast.generated.ts

  dev:
    desc: Run dev server
    deps: [ast]
    cmds:
    - npx vite --host

  check:
    desc: Check for errors
    deps: [ast]
    cmds:
    - npx tsc

  fix:
    desc: Fix errors
    cmds:
    - echo "Fix not available yet"

  test:
    desc: Run tests (Jest arguments apply)
    cmds:
    - npx jest --config tools/test/jest.config.cjs {{.ARGS}}

  build:
    desc: Build production bundle
    deps: [ast]
    cmds:
    - npx vite build
