[package]
name = "skybook-item-animated-encode"
version = "0.0.0"
edition = "2021"
description = "Encoder for animated icons"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
image = "0.25.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_yaml_ng = "0.10.0"
webp-animation = { version = "0.9.0", features = ["image"] }

[[bin]]
name = "skybook-item-animated-encode"
path = "encode.rs"

