encoder:
  # "Normal" input frame size - match the decoder config
  base_dimension: 118
  # Target frame size. If size == base then output == target
  target_dimension: 64

  # These values are optimized for size at 64x64
  # while still looking good

  # range: [0 = off .. 100 = strongest]
  # higher value will be smoother
  filter_strength: 0
  # range: [0 = off .. 7 = least sharp]
  filter_sharpness: 0
  # 0 - none, 1 - fast, 2 - best
  alpha_filtering: 2
  # Between 0 (smallest size) and 100 (lossless).
  alpha_quality: 50
  # number of entropy-analysis passes (in [1..10])
  pass: 10
  # overall quality
  quality: 90
  # Quality/speed trade-off (0=fast, 6=slower-better)
  method: 6
  # 1-4
  segments: 4

decoder:
  measurements:
    border_to_first_inner_left: 187
    border_to_first_inner_top: 335
    cell_offset: 147
    base_size: 118
    background_threshold: 0x10
    orb_erase_x:
      width: 22
      height: 20
    orb_erase_digit:
      left: 22
      bottom: 28
      width: 18
      height: 23
      erase_threshold: 72
      erase_context: 1
      fixup_left: 41   # color used to "fix" the erased part
      fixup_bottom: 23
      fixup_weight: 0.8
      fixup_iteration: 2
      fixup_context: 1
    border_erase_threshold: 0x40
  profiles:
    orb:
      frames: 240
      top_expand: 0
      erase_count: true
    travel:
      frames: 960
      top_expand: 0
      erase_count: false
    souloff:
      frames: 240
      top_expand: 0
      erase_count: false
    soulon:
      frames: 240
      top_expand: 21
      erase_count: false
    souloffdlc:
      frames: 240
      top_expand: 0
      erase_count: false
    souldlc:
      frames: 240
      top_expand: 40
      erase_count: false
      top_clean: 9
      side_expand: 3


objects:
  orb:Obj_DungeonClearSeal:
    file: video/spirit_orb.mp4
    row_col: [3, 3]
  orb:Obj_DLC_HeroSeal_Gerudo:
    file: video/naboris_orb.mp4
    row_col: [2, 1]
  orb:Obj_DLC_HeroSeal_Goron:
    file: video/rudania_orb.mp4
    row_col: [2, 2]
  orb:Obj_DLC_HeroSeal_Rito:
    file: video/medoh_orb.mp4
    row_col: [1, 4]
  orb:Obj_DLC_HeroSeal_Zora:
    file: video/ruta_orb.mp4
    row_col: [2, 0]
  travel:Obj_WarpDLC:
    file: video/travel.mp4
    row_col: [2, 3]
  souloff:Obj_HeroSoul_Gerudo_Disabled:
    file: video/soul.mp4
    row_col: [0, 4]
  souloff:Obj_HeroSoul_Goron_Disabled:
    file: video/soul.mp4
    row_col: [1, 1]
  souloff:Obj_HeroSoul_Rito_Disabled:
    file: video/soul.mp4
    row_col: [0, 2]
  souloff:Obj_HeroSoul_Zora_Disabled:
    file: video/soul.mp4
    row_col: [1, 0]
  soulon:Obj_HeroSoul_Gerudo:
    file: video/soulon.mp4
    row_col: [0, 4]
  soulon:Obj_HeroSoul_Goron:
    file: video/soulon.mp4
    row_col: [1, 1]
  soulon:Obj_HeroSoul_Rito:
    file: video/soulon.mp4
    row_col: [0, 2]
  soulon:Obj_HeroSoul_Zora:
    file: video/soulon.mp4
    row_col: [1, 0]
  souloffdlc:Obj_DLC_HeroSoul_Gerudo_Disabled:
    file: video/souloffdlc.mp4
    row_col: [1, 4]
  souloffdlc:Obj_DLC_HeroSoul_Goron_Disabled:
    file: video/souloffdlc.mp4
    row_col: [1, 2]
  souloffdlc:Obj_DLC_HeroSoul_Rito_Disabled:
    file: video/souloffdlc.mp4
    row_col: [1, 3]
  souloffdlc:Obj_DLC_HeroSoul_Zora_Disabled:
    file: video/souloffdlc.mp4
    row_col: [0, 1]
  souldlc:Obj_DLC_HeroSoul_Gerudo:
    file: video/souldlc.mp4
    row_col: [1, 4]
    top_clean_frame: 96
  souldlc:Obj_DLC_HeroSoul_Goron:
    file: video/souldlc.mp4
    row_col: [1, 2]
    top_clean_frame: 96
  souldlc:Obj_DLC_HeroSoul_Rito:
    file: video/souldlc.mp4
    row_col: [1, 3]
    top_clean_frame: 96
  souldlc:Obj_DLC_HeroSoul_Zora:
    file: video/souldlc2.mp4 # had to take another one because first row are clipped off
    row_col: [1, 0]
    top_clean_frame: 0
