version: '3'

tasks:
  pull-priv:
    desc: Pull private assets for the package. Requires gcloud access
    cmds:
      - rm -rf video
      - mkdir -p video
      - gcloud storage cp -r gs://ist-private/video .

  decode:
    desc: Decode the object
    cmds:
      - python decode.py {{.CLI_ARGS}}

  encode:
    desc: Encode the object
    cmds:
      - cargo run --release -- {{.CLI_ARGS}}

  push:
    desc: Push generated files. Requires gcloud access
    cmds:
      # The square ones are included in the sprite sheet (/Item)
      - gcloud storage cp target/encode/Obj_DungeonClearSeal.png gs://ist-private/icons/Item
      - gcloud storage cp target/encode/Obj_DLC_HeroSeal_*.png gs://ist-private/icons/Item
      - gcloud storage cp target/encode/Obj_WarpDLC.png gs://ist-private/icons/Item
      - gcloud storage cp target/encode/Obj_HeroSoul_*_Disabled.png gs://ist-private/icons/Item
      - gcloud storage cp target/encode/Obj_DLC_HeroSoul_*_Disabled.png gs://ist-private/icons/Item
      # # Activated abilities are not regular sized, so cannot be in sprite sheet
      - gcloud storage cp target/encode/Obj_HeroSoul_*.png gs://ist-private/icons/SP/Item
      - gcloud storage cp target/encode/Obj_DLC_HeroSoul_*.png gs://ist-private/icons/SP/Item
      # # Put WebPs there as well
      - gcloud storage cp target/encode/*.webp gs://ist-private/icons/SP/Item
