// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category in parser CIR
 */
export type Category =
    | "Weapon"
    | "Bow"
    | "Shield"
    | "Armor"
    | "ArmorHead"
    | "ArmorUpper"
    | "ArmorLower"
    | "Material"
    | "Food"
    | "KeyItem";
