// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic error report type with an inner error and span
 * of where the error occurred.
 */
export type ErrorReport<T> = { span: [number, number]; isWarning: boolean; error: T };
