// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of screen currently being shown. This is technically
 * not part of the pouch, but easier to think this way
 */
export type InvView_Screen = "overworld" | "inventory" | "shop";
