// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Other inventory GDT flags
 */
export type InvView_GdtInvInfo = {
    /**
     * Number of weapon slots available per tab
     */
    numWeaponSlots: number;
    /**
     * Number of bow slots available per tab
     */
    numBowSlots: number;
    /**
     * Number of shields slots available per tab
     */
    numShieldSlots: number;
    swordTabDiscovered: boolean;
    bowTabDiscovered: boolean;
    shieldTabDiscovered: boolean;
    armorTabDiscovered: boolean;
    materialTabDiscovered: boolean;
    foodTabDiscovered: boolean;
    keyItemTabDiscovered: boolean;
};
