// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Master Sword GDT flags
 */
export type InvView_GdtMasterSword = {
    /**
     * The Open_MasterSword_FullPower flag
     */
    isTrueForm: boolean;
    /**
     * The MasterSword_Add_Power flag
     */
    addPower: number;
    /**
     * The MasterSword_Add_BeamPower flag
     */
    addBeamPower: number;
    /**
     * The MasterSwordRecoverTime flag
     */
    recoverTime: number;
};
