// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_PouchItem } from "./InvView_PouchItem";
import type { InvView_PouchTab } from "./InvView_PouchTab";
import type { InvView_Screen } from "./InvView_Screen";

/**
 * List view of the Pouch Inventory.
 *
 * In this view, the inventory is represented as a vector
 * of items. Unallocated items are not included in the view.
 *
 * This view can only available if PMDM is not corrupted
 */
export type InvView_PouchList = {
    /**
     * Count of list1, as set in list1 (i.e. mCount)
     */
    count: number;
    /**
     * Actual items in list1
     */
    items: Array<InvView_PouchItem>;
    /**
     * If tab data is valid (no overflow is detected)
     */
    areTabsValid: boolean;
    /**
     * Number of tabs (mNumTabs). Should be the length
     * of the valid section of mTabs and mTabsType.
     */
    numTabs: number;
    /**
     * The actual tabs (mTabs and mTabsType), up to the tab
     * where both mTabs[i] is nullptr and mTabsType[i] is -1
     */
    tabs: Array<InvView_PouchTab>;
    /**
     * Active PE tab index
     *
     * -1 means no PE is active, 0, 1, 2 means that tab
     * and tabs 3-tabs apart are active
     */
    entangledTab: number;
    /**
     * Active PE slot index
     *
     * -1 means no PE is active, 0-19 (inclusive) corresponds
     * to the slot index
     */
    entangledSlot: number;
    /**
     * Type of the screen currently on
     */
    screen: InvView_Screen;
    /**
     * If the player is in holding state in the inventory screen,
     * note this can be true even if inventory screen is off
     */
    isHoldingInInventory: boolean;
};
