// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_CommonItem } from "./InvView_CommonItem";
import type { InvView_GdtItemData } from "./InvView_GdtItemData";

/**
 * One item in GDT
 */
export type InvView_GdtItem = {
    /**
     * Common item info
     */
    common: InvView_CommonItem;
    /**
     * Index of the item in the GDT (0-419)
     */
    idx: number;
    /**
     * Extra data that will be loaded from GDT based on the item type
     */
    data: InvView_GdtItemData;
};
