// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cook or weapon data in pouch
 */
export type InvView_ItemData = {
    /**
     * This is either the weapon modifier value,
     * or the HP recovery value for food (in quarter-hearts)
     *
     * This is the x value of StaminaRecover flag in GDT
     */
    effectValue: number;
    /**
     * For food with a timed effect, this is the duration in seconds.
     * For stamina, this is the raw value
     *
     * This is the y value of StaminaRecover flag in GDT
     */
    effectDuration: number;
    /**
     * For weapon modifier, this is the flag bitset. For food,
     * this is the sell price
     *
     * This is the x value of CookEffect1 flag in GDT
     */
    sellPrice: number;
    /**
     * Effect ID for the food
     *
     * Note this is raw memory value and may not be a valid enum value
     *
     * This is the x value of CookEffect0 flag in GDT
     */
    effectId: number;
    /**
     * The level of the effect, *usually* 1-3. However this
     * is the raw memory value and may not be valid
     *
     * This is the y value of CookEffect0 flag in GDT
     */
    effectLevel: number;
};
