// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_WeaponModifier } from "./InvView_WeaponModifier";

/**
 * Item info for something in the overworld
 */
export type InvView_OverworldItem =
    | {
          type: "equipped";
          actor: string;
          value: number;
          modifier: InvView_WeaponModifier;
      }
    | { type: "held"; actor: string }
    | {
          type: "ground-equipment";
          actor: string;
          value: number;
          modifier: InvView_WeaponModifier;
      }
    | { type: "ground-item"; actor: string };
