// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_GdtInvInfo } from "./InvView_GdtInvInfo";
import type { InvView_GdtItem } from "./InvView_GdtItem";
import type { InvView_GdtMasterSword } from "./InvView_GdtMasterSword";

/**
 * Inventory data stored in GameData (GDT)
 *
 * This contains the list of items in GDT as well as other useful flags
 */
export type InvView_Gdt = {
    items: Array<InvView_GdtItem>;
    /**
     * Master Sword flags
     */
    masterSword: InvView_GdtMasterSword;
    /**
     * Other inventory flags
     */
    info: InvView_GdtInvInfo;
};
