// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data from mTabs and mTabsType in PMDM
 *
 * Only available if PMDM is not corrupted
 */
export type InvView_PouchTab = {
    /**
     * Index of the item in the list.
     *
     * -1 if nullptr, which is when the tab is empty
     */
    itemIdx: number;
    /**
     * The type of the tab (in mTabsType), -1 if invalid
     */
    tabType: number;
};
