// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Other GDT flags
 */
export type InvView_GdtInfo = {
    /**
     * Number of weapon slots available per tab (WeaponPorchStockNum)
     */
    numWeaponSlots: number;
    /**
     * Number of bow slots available per tab (BowPorchStockNum)
     */
    numBowSlots: number;
    /**
     * Number of shields slots available per tab (ShieldPorchStockNum)
     */
    numShieldSlots: number;
    /**
     * If the Sword tab is discovered
     */
    swordTabDiscovered: boolean;
    /**
     * If the Bow tab is discovered
     */
    bowTabDiscovered: boolean;
    /**
     * If the Shield tab is discovered
     */
    shieldTabDiscovered: boolean;
    /**
     * If the Armor tab is discovered
     */
    armorTabDiscovered: boolean;
    /**
     * If the Material tab is discovered
     */
    materialTabDiscovered: boolean;
    /**
     * If the Food tab is discovered
     */
    foodTabDiscovered: boolean;
    /**
     * If the Key Items tab is discovered
     */
    keyItemTabDiscovered: boolean;
    /**
     * If the Sheika Slate was picked up
     */
    isSheikaSlateObtained: boolean;
    /**
     * If the Paraglider was picker up
     */
    isParagliderObtained: boolean;
};
