// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_OverworldItem } from "./InvView_OverworldItem";

/**
 * View of the items in the overworld (technically not inventory, but convienient to think of
 * it this way)
 */
export type InvView_Overworld = { items: Array<InvView_OverworldItem> };
