// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper for output of a task which may be aborted by calling `abort` on the handle.
 */
export type MaybeAborted<T> = { type: "Ok"; value: T } | { type: "Aborted" };
