// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pointer interop type
 *
 * This uses a u128 internal storage for a u64 value
 * to force generated bindings to convert the value to bigint
 * instead of number when sending to JS.
 */
export type Pointer = bigint;
