// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";

/**
 * Error type for the runtime
 */
export type RuntimeError =
    | { type: "CannotAutoSwitchScreen" }
    | { type: "CannotDoWhileHoldingInInventory" }
    | { type: "CannotDoWhileHoldingInOverworld" }
    | { type: "CannotFindGroundItem" }
    | { type: "CannotFindGroundItemNeedMore"; data: number }
    | { type: "CannotFindItem" }
    | { type: "CannotFindItemNeedMore"; data: number }
    | { type: "CannotFindPromptTarget" }
    | { type: "CannotGetMore" }
    | { type: "CannotHoldMore" }
    | { type: "Crash" }
    | { type: "Executor" }
    | { type: "InaccurateAllBut" }
    | { type: "InvalidItemTarget" }
    | { type: "InvalidPromptTarget" }
    | { type: "ItemMismatch"; data: [string, string] }
    | { type: "ItemMismatchCategory"; data: [string, Category] }
    | { type: "NotDroppable" }
    | { type: "NotEnoughForAllBut"; data: [number, number] }
    | { type: "NotHoldable" }
    | { type: "NotHolding" }
    | { type: "NotRightScreen" }
    | { type: "NotSellable"; data: string }
    | { type: "NotEquipment" }
    | { type: "NotEquippedInOverworld" }
    | { type: "OperationNotComplete" }
    | { type: "PositionSpecNotAllowed" }
    | { type: "PreviousCrash" }
    | { type: "Uninitialized" }
    | { type: "Unimplemented" }
    | { type: "UselessAmountForOverworldEquipment" }
    | { type: "UselessMetaForOverworldEquipment" }
    | { type: "UselessItemMatchProp" }
    | { type: "UselessScreenTransition" };
