// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error type for viewing results from the runtime
 */
export type RuntimeViewError =
    | { type: "Crash" }
    | { type: "Closed" }
    | { type: "Memory" }
    | { type: "Coherence" };
