// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error type for the runtime
 */
export type RuntimeError =
    | { type: "Uninitialized" }
    | { type: "Crash" }
    | { type: "PreviousCrash" }
    | { type: "Executor" }
    | { type: "UselessScreenTransition" }
    | { type: "NotRightScreen" }
    | { type: "Unimplemented" };
