// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error type for calling `Runtime::init`
 */
export type RuntimeInitError =
    | { type: "Executor" }
    | { type: "BadDlcVersion"; data: number }
    | { type: "UnsupportedVersion" }
    | { type: "BadImage" }
    | { type: "InvalidStackStart" }
    | { type: "InvalidPmdmAddr" }
    | { type: "ProgramStartMismatch"; data: [string, string] }
    | { type: "HeapTooBig" }
    | { type: "InitializeProcess" };
