// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for initializing a custom image
 */
export type RuntimeInitParams = {
    /**
     * DLC version to simulate
     *
     * 0 means no DLC, 1-3 means DLC version 1.0 (Day 1),
     * 2.0 (Master Trials), or 3.0 (Champion's Ballad)
     */
    dlc: number;
    /**
     * Program start address
     *
     * The string should look like 0x000000XXXXX00000, where X is a hex digit
     *
     * Unspecified (empty string) means the script can run with any program start address
     */
    programStart: string;
    /**
     * Stack start address
     *
     * The string should look like 0x000000XXXXX00000, where X is a hex digit
     *
     * Unspecified (empty string) means using the internal default
     */
    stackStart: string;
    /**
     * Size of the stack
     *
     * Unspecified, or 0, means using the internal default
     */
    stackSize: number;
    /**
     * Size of the free region of the heap
     *
     * Unspecified, or 0, means using the internal default
     */
    heapFreeSize: number;
    /**
     * Physical address of the PauseMenuDataMgr. Used to calculate heap start.
     * Should be a hex string prefixed with 0x
     *
     * Unspecified (empty string) means using the internal default
     */
    pmdmAddr: string;
};
