[package]
name = "skybook-itemsys-build"
version = "0.0.0"
edition = "2024"

[workspace]

[dependencies.cu]
package = "pistonite-cu"
version = "0.5.2"
features = [
    "cli", "fs", "yaml", "json", "derive",
    "coroutine-heavy"
]

[dependencies]
codize = "0.3.3"
serde = "1"
image = "0.25.7"
webp = "0.3.1"
webp-animation = { version = "0.9.0", features = ["image"] }
