version: '3'

includes:
  cargo:
    taskfile: ../../node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true
  

tasks:
  # -- video encoding tasks ---
  vpull-deps:
    desc: Pull the (processed) video deps
    cmds:
      - rm -f target/video/*
      - mkdir -p target/video
      - gcloud storage cp -r gs://piston-dev/botw-ist/itemsys-build/video target
  vdecode:
    desc: Decode, crop, and clean up video frames using decode.py
    cmds:
      - uv run tools/video/decode.py {{.CLI_ARGS}}
  vencode:
    desc: Encode video frames into animated webp
    cmds:
      - cargo run --bin encode --release -- {{.CLI_ARGS}}
  vpush-art:
    desc: Push encoded animated webps
    cmds:
      - gcloud storage cp -r target/encode gs://piston-dev/botw-ist/itemsys-build
  vpull-art:
    desc: Pull encoded animated webps
    cmds:
      - rm -f target/encode/*
      - mkdir -p target/encode
      - gcloud storage cp -r gs://piston-dev/botw-ist/itemsys-build/encode target

  # -- sprite rendering tasks ---
  spull-deps:
    desc: Pull the sprite deps (icons)
    cmds:
      - rm -rf target/icons/*
      - mkdir -p target/icons
      - gcloud storage cp -r gs://piston-dev/botw-ist/itemsys-build/icons target
  srender:
    desc: Render the sprites
    cmds:
      - cargo run --bin sprite --release -- {{.CLI_ARGS}}
  spush-art:
    desc: Push sprite artifacts
    cmds:
      - gcloud storage cp -r target/sprite gs://piston-dev/botw-ist/itemsys-build
  spull-art:
    desc: Pull sprite artifacts
    cmds:
      - rm -f target/sprite/*
      - mkdir -p target/sprite
      - gcloud storage cp -r gs://piston-dev/botw-ist/itemsys-build/sprite target

  # -- codegen tasks ---
  cgen:
    desc: Generate itemsys source code (requires botw-data slready built)
    cmds:
      - uv run tools/codegen/build-actor-remap.py
      - uv run tools/codegen/build-localization.py
      - uv run tools/codegen/build-actor-data-map.py
  cpush-art:
    desc: Push code artifacts to cloud
    cmds:
      - gcloud storage cp -r target/codegen gs://piston-dev/botw-ist/itemsys-build
  cpull-art:
    desc: Pull code artifacts
    cmds:
      - rm -f target/codegen/*
      - mkdir -p target/codegen
      - gcloud storage cp -r gs://piston-dev/botw-ist/itemsys-build/codegen target

  # -- dist tasks ---
  dpull-deps:
    desc: Pull deps needed for 'build'
    cmds:
      - rm -f target/images/*
      - mkdir -p target/images
      - gcloud storage cp -r gs://piston-dev/botw-ist/itemsys-build/images target

  pull-artifacts:
    desc: Pull all artifacts and build dist
    cmds:
      - task: dpull-deps
      - task: spull-art
      - task: cpull-art
      - task: vpull-art
      - task: build

  build:
    desc: Build the distribution files
    cmds:
      - rm -rf dist
      - rm -rf ../itemsys/src/generated
      - uv run tools/distbuild/distbuild.py
      - tar -czf dist/itemsys-srcgen.tar.gz -C ../itemsys/src/generated .

  pull-dist:
    desc: Pull the built distribution files from the app
    cmds:
      - rm -rf dist
      - mkdir -p dist
      - curl -fsSL -o dist/dist_index https://ist.pistonite.app/static/itemsys/dist_index
      - silent: true
        cmd: |
          echo 'pulling dist files...'
          while read -r file; do
            if [ -n "$file" ]; then
              echo "dist: $file"
              curl -fsSL -o "dist/$file" "https://ist.pistonite.app/static/itemsys/$file"
            fi
          done < dist/dist_index
      - curl -fsSL -o dist/itemsys-srcgen.tar.gz https://ist.pistonite.app/static/itemsys/itemsys-srcgen.tar.gz
      - rm -rf ../itemsys/src/generated
      - mkdir -p ../itemsys/src/generated
      - tar -xzf dist/itemsys-srcgen.tar.gz -C ../itemsys/src/generated

  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check



  clean:
    desc: Save disk space
    cmds:
      - cargo clean
      - rm -rf target
      - rm -rf .venv

