/**
 * This file is generated by workex
 */
import { type WorkexBindOptions, bindHost } from "@pistonite/workex";
import type { Application } from "../protocol.ts";

export function bindApplicationHost(delegate: Application, options: WorkexBindOptions) {
    return bindHost("skyb-0.0.1", options, (fId: number, _payload: any[]) => {
        switch (fId) {
            case 16 /* Application.getScript */: {
                return delegate.getScript();
            }
            case 17 /* Application.resolveItem */: {
                const [ a0, a1, a2 ] = _payload;
                return delegate.resolveItem( a0, a1, a2 );
            }
            case 18 /* Application.setScript */: {
                const [ a0 ] = _payload;
                return delegate.setScript( a0 );
            }
        }
        return undefined;
    });
}