/**
 * This file is generated by workex
 */
import { type WorkexBindOptions, bindHost } from "@pistonite/workex";
import type { Extension } from "../protocol.ts";

export function bindExtensionHost(delegate: Extension, options: WorkexBindOptions) {
    return bindHost("skyb-0.0.1", options, (fId: number, _payload: any[]) => {
        switch (fId) {
            case 19 /* Extension.onDarkModeChanged */: {
                const [ a0 ] = _payload;
                return delegate.onDarkModeChanged( a0 );
            }
            case 20 /* Extension.onLocaleChanged */: {
                const [ a0 ] = _payload;
                return delegate.onLocaleChanged( a0 );
            }
            case 21 /* Extension.onScriptChanged */: {
                const [ a0 ] = _payload;
                return delegate.onScriptChanged( a0 );
            }
        }
        return undefined;
    });
}