version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  build:
    desc: Generate the localization files
    aliases: [b]
    cmds:
      - python scripts/generate.py
      
  check:
    desc: Run Linter and Formatter
    cmds:
      - bun scripts/check-lang-entries.ts
      - task: ecma:tsc-check
      - task: ecma:eslint-check
      - task: ecma:prettier-check

  fix:
    desc: Fix issues in code
    cmds:
      - task: ecma:eslint-fix
      - task: ecma:prettier-fix

  put-mocks:
    cmds:
      - $(which mkdir) -p src/generated
      - cmd: "echo 'mock: mock' > src/generated/{{.ITEM}}.yaml"
        for:
          - en-US
          - ja-JP
          - de-DE
          - es-ES
          - it-IT
          - fr-FR
          - ru-RU
          - zh-CN
          - zh-TW
          - ko-KR
          - nl-NL


  push-artifacts:
    desc: Push generated files. Requires gcloud access
    cmds:
      - gcloud storage cp src/generated/* gs://ist-private/artifacts/skybook-localization/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/skybook-localization/* src/generated

