version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true

  git:
    taskfile: ./node_modules/mono-dev/task/git.yaml
    internal: true
    optional: true

tasks:
  clean:
    cmds:
      - rm -rf node_modules/.cache
      
  check:
    cmds:
      - task: ecma:check
      - node --experimental-strip-types scripts/check-lang-entries.ts
      - task: fix-language
      - task: git:check-modification
        vars:
          CHECK_PATH: packages/localization/src/ui
          CHECK_MESSAGE: Please run localization:fix task to update the translation
  fix:
    cmds:
      - task: ecma:fix
      - task: fix-language

  fix-language:
    cmds:
      - node langtool.js src/ui --no-confirm

  edit:
    desc: Make edits to the translation files
    cmds:
      - node langtool.js src/ui {{.CLI_ARGS}}
