[module]
name = "trace"
title-id = 0x01007ef00011e000

[build]
sources = [
    "src",
    "libs/botw-symbols/src",
]

includes = [
    "src",
    "libs/botw/src",
    "libs/botw/lib/agl/include",
    "libs/botw/lib/gsys/include",
    "libs/botw/lib/sead/include",
    "libs/nnheaders/include",
    "libs/botw-symbols/include",
]
ldscripts = [
    "libs/botw-symbols/ld/ld150.ld",
    "libs/botw-symbols/ld/toolkit150.ld",
]

[build.flags]
c = [
    "<default>",
    "-DNNSDK",
    "-DSWITCH",
    "-D__SWITCH__",
    "-DNN_SDK_MAJOR=4",
    "-DNN_SDK_MINOR=4",
    "-DNN_SDK_PATCH=0",
    "-DNN_WARE_MAJOR=4",
    "-DNN_WARE_MINOR=4",
    "-DNN_WARE_PATCH=0",
    "-DBOTW_VERSION=150",
    "-DBOTWTOOLKIT_TCP_SEND",
]
cxx = [
    "<default>",
    "-Wno-invalid-offsetof",
]


[check]
symbols = [
    "libs/botw-symbols/symbols/150/main.syms",
    "libs/botw-symbols/symbols/150/rtld.syms",
    "libs/botw-symbols/symbols/150/sdk.syms",
    "libs/botw-symbols/symbols/150/subsdk0.syms",
]
