[package]
name = "skybook-parser"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
cached = { version = "0.54.0", optional = true }
derive_more = { version = "1.0.0", features = ["deref", "deref_mut"] }
enumset = "1.1.6"
serde = { version = "1.0.219", features = ["derive"] }
static_assertions = "1.1.0"
teleparse = "0.0.7"
textdistance = "1.1.1"
thiserror = "2.0.12"

# TS/WASM dependencies
ts-rs = { version = "10.1.0", optional = true }
tsify-next = { version = "0.5.6", default-features = false, features = ["js"], optional = true }
wasm-bindgen = { version = "0.2.100", optional = true, features = ["serde-serialize"] }

[dev-dependencies]
anyhow = "1.0.98"
indoc = "2.0.6"
tokio = { version = "1.45.0", features = ["full"] }

[features]
__ts-binding = ["dep:ts-rs"]
wasm = ["dep:tsify-next", "dep:wasm-bindgen"]
cached = ["dep:cached"]

