[package]
name = "skybook-parser"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.skybook-api]
path = "../skybook-api"

[dependencies]
cached = { version = "0.54.0", optional = true }
derive_more.workspace = true
enumset.workspace = true
serde.workspace = true
static_assertions.workspace = true
teleparse.workspace = true
textdistance = "1.1.1"
thiserror.workspace = true

[dev-dependencies]
anyhow.workspace = true
indoc = "2.0.6"
tokio = { workspace = true, features = ["full"] }

[features]
wasm = ["skybook-api/wasm"]
cached = ["dep:cached"]

# This enables the `leak` and `from_raw` functions
# For passing ParseOutput objects to external code
unsafe-leak = []

