[package]
name = "skybook-parser"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
derive_more = { version = "1.0.0", features = ["deref", "deref_mut"] }
teleparse = "0.0.5"
textdistance = "1.1.1"
thiserror = "2.0.9"
