[package]
name = "skybook-parser"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
derive_more = { version = "1.0.0", features = ["deref", "deref_mut"] }
enumset = "1.1.5"
serde = { version = "1.0.217", features = ["derive"] }
static_assertions = "1.1.0"
teleparse = "0.0.5"
textdistance = "1.1.1"
thiserror = "2.0.9"
