version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build:
    cmds:
      - task: build-src
   
  build-src:
    cmds:
      - $(which mkdir) -p src/generated
      - python scripts/generate.py
      - task: cargo:fmt-fix

  build-api-ts-binding:
    env:
      LC_ALL: C # consistent sort order
    cmds:
      - rm -f bindings/*.ts ../skybook-api/src/parser/*
      - cargo test --lib --features __ts-binding
      - find bindings -type f | sort | sed 's/^bindings/export * from "./' | sed 's/$/";/' > index.ts
      - mv index.ts bindings
      - $(which mkdir) -p ../skybook-api/src/parser
      - mv bindings/*.ts ../skybook-api/src/parser

  test:
    cmds:
      - cargo test

  test-mocked:
    cmds:
      - cargo test --features mock-data

  test-parse:
    cmds:
      - cargo test --test parse

  test-parse-update:
    env:
      UPDATE_PARSER_SNAPSHOTS: 1
    cmds:
      - cargo test --test parse
      - cargo test --test parse --features mock-data

  check:
    cmds:
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: skybook-parser
          FEATURES: wasm,cached
      - task: cargo:fmt-check

  check-mocked:
    cmds:
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: skybook-parser
          FEATURES: mock-data
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  clean:
    cmds:
      - rm -rf src/generated

  pull-deps:
    cmds:
      - $(which mkdir) -p data
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.yaml data/

  push-artifacts:
    cmds:
      - gcloud storage cp src/generated/*.rs gs://ist-private/artifacts/skybook-parser/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.rs src/generated
