version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  bsource:
    cmds:
      - python scripts/build-armor-upgrade.py

  test:
    cmds:
      - cargo test

  test-parse:
    cmds:
      - cargo test --test parse

  update-parse-test:
    desc: Update parser tests snapshots
    aliases: [upt]
    env:
      UPDATE_PARSER_SNAPSHOTS: 1
    cmds:
      - cargo test --test parse

  check:
    cmds:
      - task: cargo:clippy-all
      - task: check-layer
      - task: cargo:fmt-check

  check-layer:
    cmds:
      - layered-crate -- check --lib --all-features

  fix:
    - task: cargo:fmt-fix

  diff:
    desc: Diff parser snapshots
    cmds:
      - delta tests/parse/{{.CLI_ARGS}} tests/parse/wip/{{.CLI_ARGS}}
