version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build:
    cmds:
      - task: build-src
   
  build-src:
    cmds:
      - $(which mkdir) -p src/generated
      - python scripts/generate.py
      - task: cargo:fmt-fix

  test:
    cmds:
      - cargo test

  test-parse:
    cmds:
      - cargo test --test parse

  update-parse-test:
    desc: Update parser tests snapshots
    aliases: [upt]
    env:
      UPDATE_PARSER_SNAPSHOTS: 1
    cmds:
      - cargo test --test parse

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  clean:
    cmds:
      - rm -rf src/generated

  diff:
    desc: Diff parser snapshots
    cmds:
      - delta tests/parse/{{.CLI_ARGS}} tests/parse/wip/{{.CLI_ARGS}}

  pull-artifacts-public:
    cmds:
      - $(which mkdir) -p src/generated
      - wget -O src/generated/item_name.rs https://skybook.pistonite.dev/botw-ist/packages/parser/item_name.rs
      - wget -O src/generated/armor_upgrade.rs https://skybook.pistonite.dev/botw-ist/packages/parser/armor_upgrade.rs

  package-artifacts-public:
    cmds:
      - $(which mkdir) -p ../manual/book/botw-ist/packages/parser
      - cp src/generated/item_name.rs ../manual/book/botw-ist/packages/parser/
      - cp src/generated/armor_upgrade.rs ../manual/book/botw-ist/packages/parser/

  push-artifacts:
    cmds:
      - gcloud storage cp src/generated/*.rs gs://ist-private/artifacts/skybook-parser/
      - gcloud storage cp data/* gs://ist-private/artifacts/skybook-parser/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.rs src/generated
