version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build-src:
    cmds:
      - $(which mkdir) -p src/generated
      - python scripts/generate.py

  test:
    cmds:
      - cargo test

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  clean:
    cmds:
      - rm -rf src/generated

  pull-deps:
    cmds:
      - $(which mkdir) -p data
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.yaml data/

  push-artifacts:
    cmds:
      - gcloud storage cp src/generated/*.rs gs://ist-private/artifacts/skybook-parser/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.rs src/generated
