version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build:
    cmds:
      - task: build-src
   
  build-src:
    cmds:
      - $(which mkdir) -p src/generated
      - python scripts/generate.py
      - task: cargo:fmt-fix

  build-api-ts-binding:
    cmds:
      - task: build-src
      - rm -f bindings/*.ts ../skybook-api/src/parser/*
      - cargo test --lib --features __ts-binding
      - find bindings -type f | sed 's/^bindings/export * from "./' | sed 's/$/";/' > bindings/index.ts
      - $(which mkdir) -p ../skybook-api/src/parser
      - mv bindings/*.ts ../skybook-api/src/parser

  test:
    cmds:
      - cargo test

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
      - task: build-binding
      - task: git:check-modification
        vars:
          CHECK_PATH: packages/parser/bindings
          CHECK_MESSAGE: Please regenerate parser bindings with `task build`

  fix:
    cmds:
      - task: cargo:fmt-fix

  clean:
    cmds:
      - rm -rf src/generated

  pull-deps:
    cmds:
      - $(which mkdir) -p data
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.yaml data/

  push-artifacts:
    cmds:
      - gcloud storage cp src/generated/*.rs gs://ist-private/artifacts/skybook-parser/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/skybook-parser/*.rs src/generated
