version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc

  test:
    cmds:
      - cargo test --lib

  check:
    cmds:
      # - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

