// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";

export type ErrorReport = {
    span: [number, number];
    is_warning: boolean;
    error: Error;
};
