// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { MetaValue } from "./MetaValue";

export type Error = { "InvalidItem": string } | "InvalidEmptyItem" | { "IntFormat": string } | { "FloatFormat": string } | { "UnusedMetaKey": string } | { "InvalidMetaValue": [string, MetaValue] } | { "InvalidWeaponModifier": string } | { "InvalidCookEffect": string } | "TooManyIngredients" | { "InvalidArmorStarNum": number } | { "InvalidSlotClause": bigint } | { "InvalidTimesClause": bigint } | { "InvalidTrial": string } | { "InvalidCategory": Category } | { "InvalidInventoryRow": bigint } | { "InvalidInventoryCol": bigint };
