// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Value in the metadata
 */
export type MetaValue = boolean | bigint | number | string;
