[book]
authors = ["Pistonight"]
language = "en"
title = "IST Simulator Manual"

[output.html]
default-theme = "frappe"
preferred-dark-theme = "frappe"
smart-punctuation = true
git-repository-url = "https://github.com/Pistonite/botw-ist"
additional-css = [
    "./theme/skybook.css",
    "./theme/extra-css/catppuccin.css", 
    "./theme/extra-css/patch.css", 
    "./src/special.css", 
]

[preprocessor.skybook]
command = "cargo run --bin skybook-manual-preprocessor --quiet"
