[package]
name = "skybook-manual-preprocessor"
version = "0.0.0"
edition = "2021"
publish = false


[dependencies.skybook-parser]
path = "../parser"

[dependencies]
cu = { workspace = true, features = ["cli", "json"] }
catppuccin = "2.5.1"
mdbook = "0.4.52"

[[bin]]
path = "preprocess/preprocess_main.rs"
name = "skybook-manual-preprocessor"
