[package]
name = "skybook-manual-preprocessor"
version = "0.0.0"
edition = "2021"
publish = false


[dependencies.skybook-parser]
path = "../parser"

[dependencies]
anyhow.workspace = true
catppuccin = "2.5.1"
clap.workspace=true
mdbook = "0.4.52"
serde_json = "1.0.142"

[[bin]]
path = "preprocess/preprocess_main.rs"
name = "skybook-manual-preprocessor"
