[package]
name = "skybook-manual-preprocessor"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
path = "preprocess/preprocess_main.rs"
name = "skybook-manual-preprocessor"

[dependencies]
anyhow = "1.0.98"
catppuccin = "2.5.1"
clap = { version = "4.5.38", features = ["derive"] }
mdbook = "0.4.49"
serde_json = "1.0.140"
skybook-parser = { path = "../parser" }
