version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
  mdbook:
    taskfile: ../mono-dev/task/mdbook.yaml
    internal: true
  parser:
    taskfile: ../parser
    dir: ../parser
    internal: true
  item-assets:
    taskfile: ../item-assets
    dir: ../item-assets
    internal: true
  item-system:
    taskfile: ../item-system
    dir: ../item-system
    internal: true
  blueflame-deps:
    taskfile: ../blueflame-deps
    dir: ../blueflame-deps
    internal: true

tasks:
  install:
    cmds:
      - task: mdbook:install-theme-monorepo
      - cargo run --bin skybook-manual-preprocessor -- style > theme/skybook.css
      - cp src/icon.svg theme/favicon.svg
      - cp src/icon.png theme/favicon.png
      - bun preprocess/inject-meta.ts pre
  dev:
    desc: Start mdbook in watch mode
    cmds:
      - task: build
      - mdbook watch &
      - live-server book -p 8081 {{.CLI_ARGS}}

  build:
    desc: (Re-)build the book
    cmds:
      - rm -rf book
      - mdbook build
      - task: parser:package-artifacts-public
      - task: item-assets:package-artifacts-public
      - task: item-system:package-artifacts-public
      - task: blueflame-deps:package-artifacts-public
      - bun preprocess/inject-meta.ts post

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix
    

