version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
  mdbook:
    taskfile: ../mono-dev/task/mdbook.yaml
    internal: true

tasks:
  install:
    cmds:
      - task: mdbook:install-theme-monorepo
      - cargo run --bin skybook-manual-preprocessor -- style > theme/skybook.css
      - cp src/icon.svg theme/favicon.svg
      - cp src/icon.png theme/favicon.png
      - bun preprocess/inject-meta.ts pre
      - $(which mkdir) -p src/generated
      - $(which mkdir) -p zh/src/generated
      - bun preprocess/generate-constants.ts
      - cp -r theme zh
  dev:
    desc: Start mdbook in watch mode
    cmds:
      - task: build
      - cmd: >
          cargo-watch --watch src --watch zh 
          -s "mdbook build && mdbook build zh -d ../book/zh" &
      - live-server book -p 8081 {{.CLI_ARGS}}

  build:
    desc: (Re-)build the book
    cmds:
      - rm -rf book
      - mdbook build
      - mdbook build zh -d ../book/zh
      - bun preprocess/inject-meta.ts post

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix
    

