version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  install:
    cmds:
      - mkdir -p theme
      - rm -f theme/*
      - cp ../mono-dev/book/theme/* theme
  dev:
    desc: Start mdbook in watch mode
    cmds:
      - task: build
      - mdbook watch &
      - live-server book -p 8081 {{.CLI_ARGS}}

  build:
    desc: (Re-)build the book
    cmds:
      - cargo run --bin skybook-manual-preprocessor -- style > theme/skybook.css
      - rm -rf book
      - mdbook build

  build-mocked:
    env:
      MDBOOK_PREPROCESSOR__SKYBOOK__COMMAND: '"cargo run --bin skybook-manual-preprocessor --quiet --features mock-data"'
    cmds:
      - cargo run --bin skybook-manual-preprocessor --features mock-data -- style > theme/skybook.css
      - rm -rf book
      - mdbook build

  check:
    cmds:
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: skybook-manual-preprocessor
          FEATURES: mock-data
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix
    

