version: '3'

includes:
  cargo:
    taskfile: ../../node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true
  mdbook:
    taskfile: ../../node_modules/mono-dev/task/mdbook.yaml
    internal: true
    optional: true

tasks:
  install:
    cmds:
      - task: mdbook:install-theme
      - cargo run --bin skybook-manual-preprocessor -- style > theme/skybook.css
      - cp src/icon.svg theme/favicon.svg
      - cp src/icon.png theme/favicon.png
      - node --experimental-strip-types preprocess/inject-meta.mts pre
      - mkdir -p src/generated
      - mkdir -p zh/src/generated
      - node --experimental-strip-types preprocess/generate-constants.mts
      - cp -r theme zh
  dev:
    desc: Start mdbook in watch mode
    cmds:
      - rm -rf book
      - shwoop book -w src -w zh --host -- {{.TASK_EXE}} build-internal

  build:
    desc: (Re-)build the book
    cmds:
      - rm -rf book
      - task: build-internal

  build-internal:
    cmds:
      - mdbook build
      - mdbook build zh -d ../book/zh
      - node --experimental-strip-types preprocess/inject-meta.mts post

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix
    

