[package]
name = "skybook-item-sprites-generator"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.94"
codize = "0.3.3"
image = "0.25.5"
num_cpus = "1.16.0"
oneshot = "0.1.8"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
threadpool = "1.8.1"
webp = "0.3.0"


[[bin]]
name = "skybook-item-sprites-generator"
path = "generator/main.rs"
