import yaml
import os

if __name__ == "__main__":
    home = os.path.dirname(os.path.realpath(__file__))
    input_path = os.path.join(home, "v3_item_names.yaml")
    with open(input_path, "r", encoding="utf-8") as f:
        item_names = yaml.safe_load(f)

    output_path = os.path.join(home, "src", "item_name_gen.rs")

    ids_by_search = []

    header = """//! This file is generated by generate-item-names.py
//! Do not edit this file manually

use crate::item_name::SearchName;

pub static ITEM_NAMES: &[SearchName] = &[
"""

    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        for item_name in sorted(item_names):
            actor_name = item_names[item_name]["actor"]
            is_material = item_names[item_name]["is_material"]
            id_len = item_names[item_name]["id_len"]
            ids_by_search.append(item_name[:id_len])
            f.write(f"SearchName::new(\"{item_name}\", \"{actor_name}\", {"true" if is_material else "false"}, {id_len}),\n")

        f.write("];\n")

    # verify search string and ids have the same sort order
    ids = list(sorted(ids_by_search))
    if ids != ids_by_search:
        print("Search string and ids have different sort order")
        exit(1)
