version: '3'

tasks:
  build-api-ts-binding:
    env:
      LC_ALL: C # consistent sort order
    cmds:
      - rm -f bindings/*.ts ../skybook-api/src/runtime/*
      - cargo test --lib --features __ts-binding
      - find bindings -type f | sort | sed 's/^bindings/export * from "./' | sed 's/$/";/' > index.ts
      - mv index.ts bindings
      - $(which mkdir) -p ../skybook-api/src/runtime
      - mv bindings/*.ts ../skybook-api/src/runtime
