version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  install:
    cmds:
      - bun scripts/generate-syntax.ts
  dev:
    desc: Run frontend app in watch mode
    cmds:
      - task: ecma:vite-dev

  clean-deps:
    desc: Delete optimized deps for local changes to take effect
    cmds:
      - rm -rf node_modules/.vite

  build:
    vars:
      COMMIT_SHORT:
        sh: git rev-parse HEAD | cut -c1-8
    desc: Build production bundle
    cmds:
      - task: ecma:vite-build
      - mv dist/popout.html dist/popout-{{.COMMIT_SHORT}}.html
      - mkdir -p dist/static/itemsys
      - cp -r ../itemsys/public/* dist/static/itemsys
  # note the runtime is packaged separately so it can be built in parallel

  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix

  test:
    cmds:
      - task: ecma:vitest

