version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  dev:
    desc: Run frontend app in watch mode
    cmds:
      - task: ecma:vite-dev

  # build:
  #   desc: Build production bundle
  #   cmds:
  #     - npx tsc
  #     - npx vite build

  check:
    desc: Check for errors
    cmds:
      - task: ecma:tsc-check-build
      - task: ecma:eslint-check
      - task: ecma:prettier-check

  fix:
    desc: Fix errors
    cmds:
      - task: ecma:eslint-fix
      - task: ecma:prettier-fix

