version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  dev:
    desc: Run frontend app in watch mode
    cmds:
      - task: ecma:vite-dev

  clean-deps:
    desc: Delete optimized deps for local changes to take effect
    cmds:
      - rm -rf node_modules/.vite

  build:
    vars:
      COMMIT_SHORT:
        sh: git rev-parse HEAD | cut -c1-8
    desc: Build production bundle
    cmds:
      - task: ecma:vite-build
      - mv dist/popout.html dist/popout-{{.COMMIT_SHORT}}.html
      - $(which mkdir) -p dist/static/item-assets
      - cp -r ../item-assets/public/* dist/static/item-assets
      - $(which mkdir) -p dist/static/item-system
      - cp -r ../item-system/public/* dist/static/item-system
  # note the runtime is packaged separately so it can be built in parallel

  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix

