version: '3'

includes:
  ecma:
    taskfile: ./node_modules/mono-dev/task/ecma.yaml
    internal: true
    optional: true
  skybook-api:
    taskfile: ../skybook-api
    internal: true
    dir: ../skybook-api
  itemsys:
    taskfile: ../itemsys
    internal: true
    dir: ../itemsys

tasks:
  install:
    cmds:
      - bun scripts/generate-syntax.ts
  dev:
    desc: Run frontend app in watch mode
    cmds:
      - task: ecma:app-dev

  build-dep:
    - task: skybook-api:build
    - task: itemsys:build

  build:
    vars:
      COMMIT_SHORT:
        sh: git rev-parse HEAD | cut -c1-8
    desc: Build production bundle
    cmds:
      - task: build-dep
      - task: ecma:app-build
      - mv dist/popout.html dist/popout-{{.COMMIT_SHORT}}.html
      - mkdir -p dist/static/itemsys
      - cp -r ../itemsys-build/public/* dist/static/itemsys
  # note the runtime is packaged separately so it can be built in parallel

  check:
    cmds:
      - task: ecma:check

  fix:
    cmds:
      - task: ecma:fix

  test:
    cmds:
      - task: ecma:test

