[book]
authors = ["Pistonight"]
language = "zh"
title = "IST 模拟器手册"

[output.html]
site-url = "/zh/"
default-theme = "frappe"
preferred-dark-theme = "frappe"
smart-punctuation = true
git-repository-url = "https://github.com/Pistonite/botw-ist"
additional-css = [
    "./theme/skybook.css",
    "./theme/extra-css/catppuccin.css", 
    "./theme/extra-css/patch.css", 
    "../src/special.css", 
]
additional-js = [
    "./src/translate-admonition.js"
]

[preprocessor.skybook]
command = "cargo run --bin skybook-manual-preprocessor --quiet"
