[package]
name = "botw-ist-command"
version = "0.0.0"
edition = "2021"

[dependencies]
logos = "0.14.1" # not needed after teleparse fix the bug
phf = { version = "0.11.2", features = ["macros"] }
teleparse = "0.0.4"
thiserror = "1.0.63"
