version: '3'

tasks:
  clean:
    cmds:
      - rm -f monaco.d.ts
      - rm -f package.original.json
      - rm -rf lib
      - rm -rf esm
      - mkdir lib
  patch:
    cmds:
      - deno --allow-read --allow-write patch.ts
      - mv lib/monaco-editor/monaco.d.ts .
      - mv lib/monaco-editor/esm .
      - mv lib/monaco-editor/package.json package.original.json
      - rm -rf lib
