[package]
name = "sim"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ist-parser = { path = "../../../sim/parser" }
ist-runtime = { path = "../../../sim/runtime" }
wasm-bindgen = "0.2.93"
