name: "Workflow Setup"
description: "Workflow Setup"

inputs:
  token:
    description: "GitHub Token"
    required: true
  rust_targets:
    description: "Targets for rust-toolchain"
    default: ""

runs:
  using: composite
  steps:
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.token }}
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: useblacksmith/setup-node@v5
      with:
        node-version: 22
        cache: 'pnpm'
    - uses: oven-sh/setup-bun@v2
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: ${{ inputs.rust_targets }}
    - uses: useblacksmith/rust-cache@v3
    - uses: taiki-e/install-action@v2
      with:
        tool: wasm-pack,mdbook,mdbook-admonish,ripgrep
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: workex
        git: https://github.com/Pistonite/workex
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        project_id: pistonstor
        workload_identity_provider: projects/262116032713/locations/global/workloadIdentityPools/github-actions/providers/github-provider
    - uses: google-github-actions/setup-gcloud@v2
