import { ActorDataMap } from "../../item-system/src/generated/ActorDataMap.ts"
import { getItemTypeAndUse, PouchItemType, PouchItemUse } from "../../item-system/src/data"

console.log("Generate PHF Map for actors");

const DEFAULT_TYPE = PouchItemType.Material;
const DEFAULT_USE = PouchItemUse.Item;

const typeMap = {};
const useMap = {};

for (const actor in ActorDataMap) {
    const [type, use] = getItemTypeAndUse(actor);
    if (type !== DEFAULT_TYPE) {
        typeMap[actor] = type;
    }
    if (use !== DEFAULT_USE) {
        useMap[actor] = use;
    }
}

console.log(Object.keys(typeMap).length, "types found");
console.log(Object.keys(useMap).length, "uses found");

const lines  = [
"//! This file is auto-generated by scripts/gen-actors.ts",
"//! DO NOT EDIT MANUALLY",
];
lines.push("#[rustfmt::skip]");
lines.push("pub static ACTOR_TYPE_MAP: phf::Map<&'static str, i32> = phf::phf_map! {");
for (const actor in typeMap) {
    lines.push(`    "${actor}" => ${typeMap[actor]},`);
}
lines.push("};");
lines.push("#[rustfmt::skip]");
lines.push("pub static ACTOR_USE_MAP: phf::Map<&'static str, i32> = phf::phf_map! {");
for (const actor in useMap) {
    lines.push(`    "${actor}" => ${useMap[actor]},`);
}
lines.push("};");

Bun.file("src/generated/actor.rs").write(lines.join("\n"))

