/**
 * This file is generated by workex
 */
import { type WorkexBindOptions, bindHost } from "@pistonite/workex";
import type { ExtensionApp } from "../ExtensionApp.ts";

export function bindExtensionAppHost(delegate: ExtensionApp, options: WorkexBindOptions) {
    return bindHost("skyb-api-0.0.1", options, (fId: number, _payload: any[]) => {
        switch (fId) {
            case 19 /* ExtensionApp.getScript */: {
                return delegate.getScript();
            }
            case 20 /* ExtensionApp.provideParserDiagnostics */: {
                const [ a0 ] = _payload;
                return delegate.provideParserDiagnostics( a0 );
            }
            case 21 /* ExtensionApp.resolveItem */: {
                const [ a0, a1, a2 ] = _payload;
                return delegate.resolveItem( a0, a1, a2 );
            }
            case 22 /* ExtensionApp.setScript */: {
                const [ a0 ] = _payload;
                return delegate.setScript( a0 );
            }
        }
        return undefined;
    });
}