/*
 * This file is generated by the workex CLI Tool
 *
 * Please visit https://workex.pistonite.dev for more information
 */

import type { WxProtocolBindConfig } from "@pistonite/workex";
import type { ExtensionApp } from "../extension_app.ts";
import type { Extension } from "../extension_api.ts";
import { _wxRecverImpl } from "./Extension.ts";
import { _wxSenderImpl } from "./ExtensionApp.ts";

/**
 * Create a bind config for the ExtensionApp interface, under the `skyb-api-0.0.3` protocol
 *
 * When used with a creator function in Workex, an implementation of ExtensionApp will be returned
 * to send remote calls to the other side. This side needs to provide an implementation for Extension
 * to be used when the other side calls this side
 *
 * This function is generated by the workex CLI tool
 */
export const skybookExtensionApp = (handler: Extension, resolve?: (_: ExtensionApp) => (void | Promise<void>)): WxProtocolBindConfig<ExtensionApp> => { return {
    protocol: "skyb-api-0.0.3",
    interfaces: ["ExtensionApp", "Extension"],
    recvHandler: _wxRecverImpl(handler),
    bindSend: (sender) => {
        const impl = new _wxSenderImpl(sender);
        resolve?.(impl);
        return impl;
    },
}};