/**
 * This file is generated by workex
 */
import { type WorkexBindOptions, bindHost } from "@pistonite/workex";
import type { RuntimeApp } from "../RuntimeApp.ts";

export function bindRuntimeAppHost(delegate: RuntimeApp, options: WorkexBindOptions) {
    return bindHost("skyb-api-0.0.1", options, (fId: number, _payload: any[]) => {
        switch (fId) {
            case 24 /* RuntimeApp.onRunCompleted */: {
                return delegate.onRunCompleted();
            }
            case 25 /* RuntimeApp.resolveQuotedItem */: {
                const [ a0 ] = _payload;
                return delegate.resolveQuotedItem( a0 );
            }
        }
        return undefined;
    });
}