/**
 * This file is generated by workex
 */
import { type WorkexBindOptions, bindHost } from "@pistonite/workex";
import type { Runtime } from "../Runtime.ts";

export function bindRuntimeHost(delegate: Runtime, options: WorkexBindOptions) {
    return bindHost("skyb-api-0.0.1", options, (fId: number, _payload: any[]) => {
        switch (fId) {
            case 24 /* Runtime.getParserDiagnostics */: {
                const [ a0 ] = _payload;
                return delegate.getParserDiagnostics( a0 );
            }
            case 25 /* Runtime.getSemanticTokens */: {
                const [ a0, a1, a2 ] = _payload;
                return delegate.getSemanticTokens( a0, a1, a2 );
            }
            case 26 /* Runtime.resolveItemIdent */: {
                const [ a0 ] = _payload;
                return delegate.resolveItemIdent( a0 );
            }
        }
        return undefined;
    });
}