version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true
  git:
    taskfile: ../mono-dev/task/git.yaml
    internal: true

tasks:
  build:
    cmds:
      - workex -p runtime src/protocol.ts --no-gitignore

  check:
    cmds:
      - task: ecma:tsc-check
      - task: ecma:prettier-check
      - task: build
      - task: git:check-modification
        vars:
          CHECK_PATH: packages/runtime-api/src
          CHECK_MESSAGE: Please regenerate runtime-api source with `task build`

  fix:
    cmds:
      - task: ecma:prettier-fix
