version: '3'

includes:
  cargo:
    taskfile: ../../node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  build-src:
    - mkdir -p src/generated
    - uv run scripts/generate.py
    - node scripts/gen-actors.mts
    - task: cargo:fmt-fix

  test:
    - cargo test --features data

  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check

  fix:
    - task: cargo:fmt-fix

  push-artifacts:
    - gcloud storage cp -r src/generated gs://piston-dev/botw-ist/blueflame-deps/generated

  pull-artifacts:
    - rm -f src/generated/*
    - mkdir -p src/generated
    - gcloud storage cp -r gs://piston-dev/botw-ist/blueflame-deps/generated src
