version: '3'

includes:
  cargo:
    taskfile: ../../node_modules/mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  build-src:
    - mkdir -p src/generated
    - uv run scripts/generate.py
    - node scripts/gen-actors.mts
    - task: cargo:fmt-fix

  test:
    - cargo test --features data

  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check

  fix:
    - task: cargo:fmt-fix

  push-artifacts:
    - gcloud storage cp src/generated/* gs://ist-private/artifacts/blueflame-deps/

  pull-artifacts:
    - mkdir -p src/generated
    - gcloud storage cp gs://ist-private/artifacts/blueflame-deps/* src/generated
