version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build:
    - task: build-src
   
  build-src:
    - $(which mkdir) -p src/generated
    - python scripts/generate.py
    - bun scripts/gen-actors.ts
    - task: cargo:fmt-fix

  test:
    - cargo test --features data

  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check

  fix:
    - task: cargo:fmt-fix

  push-artifacts:
    - gcloud storage cp src/generated/* gs://ist-private/artifacts/blueflame-deps/

  pull-artifacts:
    - $(which mkdir) -p src/generated
    - gcloud storage cp gs://ist-private/artifacts/blueflame-deps/* src/generated
