version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build:
    cmds:
      - task: build-src
   
  build-src:
    cmds:
      - $(which mkdir) -p src/generated
      - python scripts/generate.py
      - bun scripts/gen-actors.ts
      - task: cargo:fmt-fix

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  pull-artifacts-public:
    cmds:
      - $(which mkdir) -p src/generated
      - wget -O src/generated/gdt.rs https://skybook.pistonite.dev/botw-ist/packages/blueflame-deps/gdt.rs
      - wget -O src/generated/actor.rs https://skybook.pistonite.dev/botw-ist/packages/blueflame-deps/actor.rs

  package-artifacts-public:
    cmds:
      - $(which mkdir) -p ../manual/book/botw-ist/packages/blueflame-deps
      - cp src/generated/gdt.rs ../manual/book/botw-ist/packages/blueflame-deps/
      - cp src/generated/actor.rs ../manual/book/botw-ist/packages/blueflame-deps/

  push-artifacts:
    cmds:
      - gcloud storage cp src/generated/*.rs gs://ist-private/artifacts/blueflame-deps/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/blueflame-deps/*.rs src/generated
