// This has RS extension since that usually gives a minimal syntax highlighting.
//This is not an actual RS file

x!{ SKYBOOK RUNTIME SNAPSHOT V1

=====

----- Step[0]: get 6 apple 7 banana 8 shroom 9 pepper 10 durian

game: (Running)
  screen: (Overworld)
  pouch: (count=5, are_tabs_valid=true, num_tabs=1, holding_in_inventory=false, )
    items: (len=5, )
      [000]: (actor_name=Item_Fruit_A, value=6, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=0, )
        node: (valid=true, pos=419, addr=0x0000002222243f68, prev=0x0000002222200068, next=0x0000002222243cd0, )
      [001]: (actor_name=Item_Fruit_H, value=7, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=1, )
        node: (valid=true, pos=418, addr=0x0000002222243cd0, prev=0x0000002222243f68, next=0x0000002222243a38, )
      [002]: (actor_name=Item_Mushroom_E, value=8, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=2, )
        node: (valid=true, pos=417, addr=0x0000002222243a38, prev=0x0000002222243cd0, next=0x00000022222437a0, )
      [003]: (actor_name=Item_Fruit_I, value=9, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=3, )
        node: (valid=true, pos=416, addr=0x00000022222437a0, prev=0x0000002222243a38, next=0x0000002222243508, )
      [004]: (actor_name=Item_Fruit_D, value=10, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=4, )
        node: (valid=true, pos=415, addr=0x0000002222243508, prev=0x00000022222437a0, next=0x0000002222200068, )
    tabs: (len=1, )
      [00]: (item_idx=0, tab_type=Material, )

----- Step[1]: drop all apple all shroom all durian

game: (Running)
  screen: (Overworld)
  pouch: (count=2, are_tabs_valid=true, num_tabs=1, holding_in_inventory=false, )
    items: (len=2, )
      [000]: (actor_name=Item_Fruit_H, value=7, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=0, )
        node: (valid=true, pos=418, addr=0x0000002222243cd0, prev=0x0000002222200068, next=0x00000022222437a0, )
      [001]: (actor_name=Item_Fruit_I, value=9, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=1, )
        node: (valid=true, pos=416, addr=0x00000022222437a0, prev=0x0000002222243cd0, next=0x0000002222200068, )
    tabs: (len=1, )
      [00]: (item_idx=0, tab_type=Material, )
  overworld: (len=24, )
      [000]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [001]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [002]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [003]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [004]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [005]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [006]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [007]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [008]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [009]: (typ=GroundItem, actor=Item_Fruit_D, despawning=false, )
      [010]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [011]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [012]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [013]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [014]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [015]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [016]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [017]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [018]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [019]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [020]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [021]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [022]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [023]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )

----- Step[2]: drop all but 1 banana all but 5 pepper

game: (Running)
  screen: (Overworld)
  pouch: (count=2, are_tabs_valid=true, num_tabs=1, holding_in_inventory=false, )
    items: (len=2, )
      [000]: (actor_name=Item_Fruit_H, value=1, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=0, )
        node: (valid=true, pos=418, addr=0x0000002222243cd0, prev=0x0000002222200068, next=0x00000022222437a0, )
      [001]: (actor_name=Item_Fruit_I, value=5, is_equipped=false, item_type=Material, item_use=CureItem, tab_idx=0, tab_slot=1, )
        node: (valid=true, pos=416, addr=0x00000022222437a0, prev=0x0000002222243cd0, next=0x0000002222200068, )
    tabs: (len=1, )
      [00]: (item_idx=0, tab_type=Material, )
  overworld: (len=34, )
      [000]: (typ=GroundItem, actor=Item_Fruit_H, despawning=false, )
      [001]: (typ=GroundItem, actor=Item_Fruit_H, despawning=false, )
      [002]: (typ=GroundItem, actor=Item_Fruit_H, despawning=false, )
      [003]: (typ=GroundItem, actor=Item_Fruit_H, despawning=false, )
      [004]: (typ=GroundItem, actor=Item_Fruit_H, despawning=false, )
      [005]: (typ=GroundItem, actor=Item_Fruit_H, despawning=false, )
      [006]: (typ=GroundItem, actor=Item_Fruit_I, despawning=false, )
      [007]: (typ=GroundItem, actor=Item_Fruit_I, despawning=false, )
      [008]: (typ=GroundItem, actor=Item_Fruit_I, despawning=false, )
      [009]: (typ=GroundItem, actor=Item_Fruit_I, despawning=false, )
      [010]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [011]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [012]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [013]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [014]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [015]: (typ=GroundItem, actor=Item_Fruit_A, despawning=true, )
      [016]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [017]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [018]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [019]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [020]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [021]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [022]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [023]: (typ=GroundItem, actor=Item_Mushroom_E, despawning=true, )
      [024]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [025]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [026]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [027]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [028]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [029]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [030]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [031]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [032]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )
      [033]: (typ=GroundItem, actor=Item_Fruit_D, despawning=true, )

}
