// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemSlotInfo } from "./ItemSlotInfo";

/**
 * Inventory data stored in GameData (GDT)
 *
 * This contains the list of items in GDT as well as other useful flags
 */
export type GameDataInventory = { items: Array<ItemSlotInfo> };
