// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryInfo } from "./InventoryInfo";
import type { OffsetListInfo } from "./OffsetListInfo";

export type InventoryGraphView = {
    info: InventoryInfo;
    list1: OffsetListInfo;
    list2: OffsetListInfo;
    /**
     * Node address to the item slot info read from memory for that node
     *
     * Note the addresses are for the *node*, not the PouchItem
     */
    nodes: Map<Pointer, ItemSlotInfo>;
};
import type { ItemSlotInfo } from "./ItemSlotInfo";
import type { Pointer } from "./Pointer";
