// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabInfo } from "./TabInfo";

/**
 * Common inventory info in different inventory views
 */
export type InventoryInfo = {
    /**
     * Number of tabs (mNumTabs). Should be the length
     * of the valid section of mTabs and mTabsType
     */
    numTabs: number;
    tabs: Array<TabInfo>;
};
