// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryInfo } from "./InventoryInfo";
import type { ItemSlotInfo } from "./ItemSlotInfo";

/**
 * List view of the inventory.
 *
 * In this view, the inventory is represented as a vector
 * of items. Unallocated items are not included in the view.
 *
 * Only valid if all internal PouchItem pointer references
 * are valid in PMDM, and mListHeads references (PouchItem**)
 * are either nullptr, or points to element in mTabs
 */
export type InventoryListView = {
    info: InventoryInfo;
    items: Array<ItemSlotInfo>;
    count: number;
};
