// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_PouchData } from "./InvView_PouchData";
import type { InvView_PouchItem } from "./InvView_PouchItem";

/**
 * List view of the Pouch Inventory.
 *
 * In this view, the inventory is represented as a vector
 * of items. Unallocated items are not included in the view.
 *
 * Only valid if all internal PouchItem pointer references
 * are valid in PMDM, and mListHeads references (PouchItem**)
 * are either nullptr, or points to element in mTabs
 */
export type InvView_PouchList = {
    info: InvView_PouchData;
    items: Array<InvView_PouchItem>;
    count: number;
};
