// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_PouchTab } from "./InvView_PouchTab";

/**
 * Common Pouch (PMDM) fields in list and graph views
 */
export type InvView_PouchData = {
    /**
     * Number of tabs (mNumTabs). Should be the length
     * of the valid section of mTabs and mTabsType
     */
    numTabs: number;
    tabs: Array<InvView_PouchTab>;
};
