// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weapon modifier info, which is a bitflag for modifier type and a modifier value
 */
export type InvView_WeaponModifier = { flag: number; value: number };
