// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pointer } from "./Pointer";

/**
 * Data from mTabs and mTabsType in PMDM
 */
export type InvView_PouchTab = {
    itemIdx: number | undefined;
    itemPtr: Pointer;
    tabType: number;
};
