// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvView_WeaponModifier } from "./InvView_WeaponModifier";

/**
 * Item info for something in the overworld
 */
export type InvView_OverworldItem =
    | {
          type: "equipped";
          data: {
              actor: string;
              value: number;
              modifier: InvView_WeaponModifier;
          };
      }
    | { type: "held"; data: { actor: string } }
    | {
          type: "groundEquipment";
          data: {
              actor: string;
              value: number;
              modifier: InvView_WeaponModifier;
          };
      }
    | { type: "groundItem"; data: { actor: string } };
