// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pointer } from "./Pointer";

export type OffsetListInfo = {
    /**
     * Address of the mStartEnd node of the list
     */
    headPtr: Pointer;
    /**
     * mStartEnd::mPrev
     */
    prevNodePtr: Pointer;
    /**
     * mStartEnd::mNext
     */
    nextNodePtr: Pointer;
    /**
     * mCount
     */
    count: number;
    /**
     * mOffset
     */
    offset: number;
};
