// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeInitOutput = {
    /**
     * "1.5" or "1.6"
     */
    gameVersion: string;
};
