// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeInitError =
    | { type: "BadDlcVersion"; data: number }
    | { type: "BadImage" }
    | { type: "InvalidProgramStart" }
    | { type: "InvalidStackStart" }
    | { type: "InvalidPmdmAddr" }
    | { type: "ProgramStartMismatch"; data: [string, string] };
