// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pointer } from "./Pointer";

export type TabInfo = {
    itemIdx: number | undefined;
    itemPtr: Pointer;
    tabType: number;
};
