version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  build:
    vars:
      VERSION:
        sh: jq '.version' package.json | tr -d '"'
    cmds:
      - workex -p skyb-{{.VERSION}} src/protocol.ts

  check:
    cmds:
      - task: ecma:tsc-check
      - task: ecma:prettier-check

  fix:
    cmds:
      - task: ecma:prettier-fix
