version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  build:
    cmds:
      - wasm-pack build -t no-modules --no-pack
      - task: build-dist

  build-dist:
    vars:
      BUILD_DIR: dist
    cmds:
      - $(which mkdir) -p {{.BUILD_DIR}}
      - cp pkg/skybook_runtime_wasm.js {{.BUILD_DIR}}/worker.js
      - cp pkg/skybook_runtime_wasm_bg.wasm {{.BUILD_DIR}}/skybook.wasm
      - bun build src/worker.ts >> {{.BUILD_DIR}}/worker.js

  check:
    desc: Run Linter and Formatter
    cmds:
      - task: ecma:tsc-check
      - task: ecma:eslint-check
      - task: ecma:prettier-check

  fix:
    desc: Fix issues in code
    cmds:
      - task: ecma:eslint-fix
      - task: ecma:prettier-fix
