version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true

tasks:
  build:
    cmds:
      - task: build-wasm
      - task: build-dist

  build-mocked:
    cmds:
      - wasm-pack build -t no-modules --no-pack --dev -- --features mock-data
      - task: build-dist

  build-wasm:
    cmds:
      - wasm-pack build -t no-modules --no-pack

  build-dist:
    vars:
      BUILD_DIR: dist
    cmds:
      - $(which mkdir) -p {{.BUILD_DIR}}
      - cp pkg/skybook_runtime_wasm.js {{.BUILD_DIR}}/worker.js
      - cp pkg/skybook_runtime_wasm_bg.wasm {{.BUILD_DIR}}/skybook.wasm
      - bun build src/worker.ts >> {{.BUILD_DIR}}/worker.js

  check:
    desc: Run Linter and Formatter
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
      - task: ecma:tsc-check
      - task: ecma:eslint-check
      - task: ecma:prettier-check

  check-mocked:
    cmds:
      - task: cargo:clippy-package-feature
        vars:
          PACKAGE: skybook-runtime-wasm
          FEATURES: mock-data
      - task: cargo:fmt-check
      - task: ecma:tsc-check
      - task: ecma:eslint-check
      - task: ecma:prettier-check

  fix:
    desc: Fix issues in code
    cmds:
      - task: cargo:fmt-fix
      - task: ecma:eslint-fix
      - task: ecma:prettier-fix
