[package]
name = "blueflame-utils"
version = "0.0.0"
edition = "2021"
description = "Basic shared util types for BlueFlame"

[dependencies]
deku = { version = "0.19.0", optional = true }
enum-map = { version = "2.7.3", optional = true }
serde = { version = "1.0.217", features = ["derive"], optional = true }

[features]
deku = ["dep:deku"]
serde = ["dep:serde"]
enum-map = ["dep:enum-map"]
