name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-app-manual-server:
    if: github.event_name == 'pull_request'
    name: app-manual-server
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          ecma-pnpm: true
          ecma-bun: true
          rust: stable
          tool-mdbook: true
          tool-cargo-binstall: workex=Pistonite/workex
          python: uv
      - uses: ./.github/steps/cache-ci
        with:
          itemsys: true
      - run: task build-app-manual-server-ci
      - uses: actions/upload-artifact@v7
        with:
          path: packages/app/dist
          name: app
          retention-days: 3
      - uses: actions/upload-artifact@v7
        with:
          path: packages/server/dist
          name: server
          retention-days: 3

  build-app-server:
    if: github.event_name != 'pull_request'
    name: app-server
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          ecma-pnpm: true
          ecma-bun: true
          rust: stable
          tool-cargo-binstall: workex=Pistonite/workex
          python: uv
      - uses: ./.github/steps/cache-ci
        with:
          itemsys: true
      - run: task build-app-server-ci
      - uses: actions/upload-artifact@v7
        with:
          path: packages/app/dist
          name: app
          retention-days: 3
      - uses: actions/upload-artifact@v7
        with:
          path: packages/server/dist
          name: server
          retention-days: 3

  build-runtime-wasm:
    name: runtime-wasm
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          ecma-pnpm: true
          ecma-bun: true
          rust: nightly
          rust-wasm: true
          rust-src: true
          tool-cargo-binstall: workex=Pistonite/workex
      - uses: ./.github/steps/cache-ci
        with:
          runtime: true
      - if: github.event_name != 'pull_request'
        run: task build-runtime-ci
      - if: github.event_name == 'pull_request'
        run: task build-runtime-ci-pr
      - uses: actions/upload-artifact@v7
        with:
          path: packages/runtime-wasm/dist
          name: runtime
          retention-days: 3

