name: Docker
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    # permission for publishing docker image
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - uses: oven-sh/setup-bun@v2
      - uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      # download artifacts
      - run: mkdir -p packages/server/dist
      - uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          commit: ${{ github.sha }}
          path: packages/server/dist
      - run: |
          mv packages/server/dist/server/server-bin packages/server/dist
          rm -r packages/server/dist/server
      - run: task package-assets
        working-directory: packages/server
      - id: set-version
        working-directory: packages/server
        run: echo "version=$(bun scripts/get-version.ts)" >> "$GITHUB_OUTPUT"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/pistonite/skybook-server
          tags: |
            type=sha
            type=sha,format=long
            type=raw,value=${{ steps.set-version.outputs.version }}
            type=raw,value=latest
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: packages/server
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


