name: IST Simulator - CI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm ci
    - run: task check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm ci
    - run: task test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm ci
    - run: task build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist
        retention-days: 3

  deploy:
    name: Deploy
    needs:
    - build
    - test
    if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
