[package]
name = "item-sprites-generator"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.94"
codize = "0.3.3"
image = "0.25.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.9"
webp = "0.3.0"


[[bin]]
name = "item-sprites-generator"
path = "generator/main.rs"
