version: '3'

includes:
  ecma:
    taskfile: ../mono-dev/task/ecma.yaml
    internal: true

tasks:
  dev:
    desc: Run test page dev server
    cmds:
      - task: ecma:vite-dev

  build:
    cmds:
      - $(which mkdir) -p src/generated
      - python scripts/generate.py

  check:
    cmds:
      - task: ecma:mono-check

  fix:
    cmds:
      - task: ecma:mono-fix

  test:
    cmds:
      - task: ecma:vite-build

  push-artifacts:
    cmds:
      - gcloud storage cp src/generated/*.ts gs://ist-private/artifacts/skybook-item-system/

  pull-artifacts-public:
    cmds:
      - $(which mkdir) -p src/generated
      - wget -O src/generated/ActorDataMap.ts https://skybook.pistonite.dev/botw-ist/packages/item-system/ActorDataMap.ts

  package-artifacts-public:
    cmds:
      - $(which mkdir) -p ../manual/book/botw-ist/packages/item-system
      - cp src/generated/ActorDataMap.ts ../manual/book/botw-ist/packages/item-system/

  pull-artifacts:
    cmds:
      - $(which mkdir) -p public
      - gcloud storage cp gs://ist-private/images/SheikahBackground*.png public
      - gcloud storage cp gs://ist-private/images/bg-*.jpg public
      - task: pull-artifacts-ts

  pull-artifacts-ts:
    cmds:
      - $(which mkdir) -p src/generated
      - gcloud storage cp gs://ist-private/artifacts/skybook-item-system/*.ts src/generated
